/*** Autogenerated by WIDL 9.21 from dlls/schedsvc/schrpc.idl - Do not edit ***/
#include <string.h>

#include "schrpc.h"

#define TYPE_FORMAT_STRING_SIZE 507
#define PROC_FORMAT_STRING_SIZE 1127

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

/*****************************************************************************
 * ITaskSchedulerService interface
 */

static RPC_DISPATCH_TABLE ITaskSchedulerService_v1_0_DispatchTable;
static const MIDL_SERVER_INFO ITaskSchedulerService_ServerInfo;

static const RPC_SERVER_INTERFACE ITaskSchedulerService___RpcServerInterface =
{
    sizeof(RPC_SERVER_INTERFACE),
    {{0x86d35949,0x83c9,0x4044,{0xb4,0x24,0xdb,0x36,0x32,0x31,0xfd,0x0c}},{1,0}},
    {{0x8a885d04,0x1ceb,0x11c9,{0x9f,0xe8,0x08,0x00,0x2b,0x10,0x48,0x60}},{2,0}},
    &ITaskSchedulerService_v1_0_DispatchTable,
    0,
    0,
    0,
    &ITaskSchedulerService_ServerInfo,
    0,
};
RPC_IF_HANDLE ITaskSchedulerService_v1_0_s_ifspec = (RPC_IF_HANDLE)& ITaskSchedulerService___RpcServerInterface;

static const MIDL_STUB_DESC ITaskSchedulerService_StubDesc;

#if !defined(__RPC_WIN64__)
#error  Invalid build platform for this stub.
#endif

static const unsigned short ITaskSchedulerService_FormatStringOffsetTable[] =
{
    0,  /* SchRpcHighestVersion */
    38,  /* SchRpcRegisterTask */
    124,  /* SchRpcRetrieveTask */
    180,  /* SchRpcCreateFolder */
    230,  /* SchRpcSetSecurity */
    280,  /* SchRpcGetSecurity */
    330,  /* SchRpcEnumFolders */
    398,  /* SchRpcEnumTasks */
    466,  /* SchRpcEnumInstances */
    522,  /* SchRpcGetInstanceInfo */
    602,  /* SchRpcStopInstance */
    646,  /* SchRpcStop */
    690,  /* SchRpcRun */
    764,  /* SchRpcDelete */
    808,  /* SchRpcRename */
    858,  /* SchRpcScheduledRuntimes */
    932,  /* SchRpcGetLastRunInfo */
    982,  /* SchRpcGetTaskInfo */
    1038,  /* SchRpcGetNumberOfMissedRuns */
    1082,  /* SchRpcEnableTask */
};

static const MIDL_STUB_DESC ITaskSchedulerService_StubDesc =
{
    (void *)& ITaskSchedulerService___RpcServerInterface,
    MIDL_user_allocate,
    MIDL_user_free,
    {
        0,
    },
    0,
    0,
    0,
    0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};

static RPC_DISPATCH_FUNCTION ITaskSchedulerService_table[] =
{
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    0
};
static RPC_DISPATCH_TABLE ITaskSchedulerService_v1_0_DispatchTable =
{
    20,
    ITaskSchedulerService_table
};

static const SERVER_ROUTINE ITaskSchedulerService_ServerRoutineTable[] =
{
    (void *)SchRpcHighestVersion,
    (void *)SchRpcRegisterTask,
    (void *)SchRpcRetrieveTask,
    (void *)SchRpcCreateFolder,
    (void *)SchRpcSetSecurity,
    (void *)SchRpcGetSecurity,
    (void *)SchRpcEnumFolders,
    (void *)SchRpcEnumTasks,
    (void *)SchRpcEnumInstances,
    (void *)SchRpcGetInstanceInfo,
    (void *)SchRpcStopInstance,
    (void *)SchRpcStop,
    (void *)SchRpcRun,
    (void *)SchRpcDelete,
    (void *)SchRpcRename,
    (void *)SchRpcScheduledRuntimes,
    (void *)SchRpcGetLastRunInfo,
    (void *)SchRpcGetTaskInfo,
    (void *)SchRpcGetNumberOfMissedRuns,
    (void *)SchRpcEnableTask,
};

static const MIDL_SERVER_INFO ITaskSchedulerService_ServerInfo =
{
    &ITaskSchedulerService_StubDesc,
    ITaskSchedulerService_ServerRoutineTable,
    __MIDL_ProcFormatString.Format,
    ITaskSchedulerService_FormatStringOffsetTable,
    0,
    0,
    0,
    0
};

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure ITaskSchedulerService::SchRpcHighestVersion) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x0),	/* method 0 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x44,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 26 (parameter version) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x09,	/* FC_ULONG */
        0x0,
/* 32 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 38 (procedure ITaskSchedulerService::SchRpcRegisterTask) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x1),	/* method 1 */
        NdrFcShort(0x50),	/* stack size = 80 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x0a,	/* 10 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 64 (parameter path) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x6),	/* type offset = 6 */
/* 70 (parameter xml) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xc),	/* type offset = 12 */
/* 76 (parameter flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 82 (parameter sddl) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0xe),	/* type offset = 14 */
/* 88 (parameter task_logon_type) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 94 (parameter n_creds) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x28),	/* stack offset = 40 */
        0x08,	/* FC_LONG */
        0x0,
/* 100 (parameter creds) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x30),	/* stack offset = 48 */
        NdrFcShort(0x46),	/* type offset = 70 */
/* 106 (parameter actual_path) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x38),	/* stack offset = 56 */
        NdrFcShort(0x4e),	/* type offset = 78 */
/* 112 (parameter xml_error_info) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x40),	/* stack offset = 64 */
        NdrFcShort(0x74),	/* type offset = 116 */
/* 118 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x48),	/* stack offset = 72 */
        0x08,	/* FC_LONG */
        0x0,
/* 124 (procedure ITaskSchedulerService::SchRpcRetrieveTask) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x2),	/* method 2 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x05,	/* 5 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 150 (parameter path) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x7a),	/* type offset = 122 */
/* 156 (parameter languages) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x7e),	/* type offset = 126 */
/* 162 (parameter n_languages) */
        NdrFcShort(0x148),	/* flags: in, base type, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x09,	/* FC_ULONG */
        0x0,
/* 168 (parameter xml) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x88),	/* type offset = 136 */
/* 174 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 180 (procedure ITaskSchedulerService::SchRpcCreateFolder) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 206 (parameter path) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x8e),	/* type offset = 142 */
/* 212 (parameter sddl) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x90),	/* type offset = 144 */
/* 218 (parameter flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 224 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 230 (procedure ITaskSchedulerService::SchRpcSetSecurity) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 256 (parameter path) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x96),	/* type offset = 150 */
/* 262 (parameter sddl) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x9a),	/* type offset = 154 */
/* 268 (parameter flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 274 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 280 (procedure ITaskSchedulerService::SchRpcGetSecurity) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 306 (parameter path) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x9e),	/* type offset = 158 */
/* 312 (parameter flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 318 (parameter sddl) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0xa4),	/* type offset = 164 */
/* 324 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 330 (procedure ITaskSchedulerService::SchRpcEnumFolders) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0x38),	/* stack size = 56 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x18),	/* server buffer = 24 */
        0x47,
        0x07,	/* 7 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 356 (parameter path) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0xaa),	/* type offset = 170 */
/* 362 (parameter flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 368 (parameter start_index) */
        NdrFcShort(0x158),	/* flags: in, out, base type, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x09,	/* FC_ULONG */
        0x0,
/* 374 (parameter n_requested) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 380 (parameter n_names) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x09,	/* FC_ULONG */
        0x0,
/* 386 (parameter names) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0xce),	/* type offset = 206 */
/* 392 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x30),	/* stack offset = 48 */
        0x08,	/* FC_LONG */
        0x0,
/* 398 (procedure ITaskSchedulerService::SchRpcEnumTasks) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x7),	/* method 7 */
        NdrFcShort(0x38),	/* stack size = 56 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x18),	/* server buffer = 24 */
        0x47,
        0x07,	/* 7 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 424 (parameter path) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0xd4),	/* type offset = 212 */
/* 430 (parameter flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 436 (parameter start_index) */
        NdrFcShort(0x158),	/* flags: in, out, base type, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x09,	/* FC_ULONG */
        0x0,
/* 442 (parameter n_requested) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 448 (parameter n_names) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x09,	/* FC_ULONG */
        0x0,
/* 454 (parameter names) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0xf8),	/* type offset = 248 */
/* 460 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x30),	/* stack offset = 48 */
        0x08,	/* FC_LONG */
        0x0,
/* 466 (procedure ITaskSchedulerService::SchRpcEnumInstances) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x8),	/* method 8 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x47,
        0x05,	/* 5 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 492 (parameter path) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0xfc),	/* type offset = 252 */
/* 498 (parameter flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 504 (parameter n_guids) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x09,	/* FC_ULONG */
        0x0,
/* 510 (parameter guids) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x12a),	/* type offset = 298 */
/* 516 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 522 (procedure ITaskSchedulerService::SchRpcGetInstanceInfo) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x9),	/* method 9 */
        NdrFcShort(0x48),	/* stack size = 72 */
        NdrFcShort(0x14),	/* client buffer = 20 */
        NdrFcShort(0x20),	/* server buffer = 32 */
        0x45,
        0x09,	/* 9 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 548 (parameter guid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x10a),	/* type offset = 266 */
/* 554 (parameter path) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x132),	/* type offset = 306 */
/* 560 (parameter task_state) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x09,	/* FC_ULONG */
        0x0,
/* 566 (parameter action) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x13e),	/* type offset = 318 */
/* 572 (parameter info) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x146),	/* type offset = 326 */
/* 578 (parameter n_instances) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x28),	/* stack offset = 40 */
        0x09,	/* FC_ULONG */
        0x0,
/* 584 (parameter instances) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x30),	/* stack offset = 48 */
        NdrFcShort(0x162),	/* type offset = 354 */
/* 590 (parameter pid) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x38),	/* stack offset = 56 */
        0x09,	/* FC_ULONG */
        0x0,
/* 596 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x40),	/* stack offset = 64 */
        0x08,	/* FC_LONG */
        0x0,
/* 602 (procedure ITaskSchedulerService::SchRpcStopInstance) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xa),	/* method 10 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x1c),	/* client buffer = 28 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 628 (parameter guid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x10a),	/* type offset = 266 */
/* 634 (parameter flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 640 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 646 (procedure ITaskSchedulerService::SchRpcStop) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xb),	/* method 11 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 672 (parameter path) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x16a),	/* type offset = 362 */
/* 678 (parameter flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 684 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 690 (procedure ITaskSchedulerService::SchRpcRun) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xc),	/* method 12 */
        NdrFcShort(0x40),	/* stack size = 64 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x1c),	/* server buffer = 28 */
        0x46,
        0x08,	/* 8 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 716 (parameter path) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x170),	/* type offset = 368 */
/* 722 (parameter n_args) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 728 (parameter args) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x188),	/* type offset = 392 */
/* 734 (parameter flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 740 (parameter session_id) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 746 (parameter user) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0x18c),	/* type offset = 396 */
/* 752 (parameter guid) */
        NdrFcShort(0x4112),	/* flags: must free, out, simple ref, srv size=16 */
        NdrFcShort(0x30),	/* stack offset = 48 */
        NdrFcShort(0x10a),	/* type offset = 266 */
/* 758 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x38),	/* stack offset = 56 */
        0x08,	/* FC_LONG */
        0x0,
/* 764 (procedure ITaskSchedulerService::SchRpcDelete) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xd),	/* method 13 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 790 (parameter path) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x196),	/* type offset = 406 */
/* 796 (parameter flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 802 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 808 (procedure ITaskSchedulerService::SchRpcRename) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xe),	/* method 14 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 834 (parameter path) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x19a),	/* type offset = 410 */
/* 840 (parameter name) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x19e),	/* type offset = 414 */
/* 846 (parameter flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 852 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 858 (procedure ITaskSchedulerService::SchRpcScheduledRuntimes) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xf),	/* method 15 */
        NdrFcShort(0x40),	/* stack size = 64 */
        NdrFcShort(0x44),	/* client buffer = 68 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x47,
        0x08,	/* 8 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 884 (parameter path) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x1a2),	/* type offset = 418 */
/* 890 (parameter start) */
        NdrFcShort(0xa),	/* flags: must free, in */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x1b2),	/* type offset = 434 */
/* 896 (parameter end) */
        NdrFcShort(0xa),	/* flags: must free, in */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x1b6),	/* type offset = 438 */
/* 902 (parameter flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 908 (parameter n_requested) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 914 (parameter n_runtimes) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x28),	/* stack offset = 40 */
        0x09,	/* FC_ULONG */
        0x0,
/* 920 (parameter runtimes) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x30),	/* stack offset = 48 */
        NdrFcShort(0x1d2),	/* type offset = 466 */
/* 926 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x38),	/* stack offset = 56 */
        0x08,	/* FC_LONG */
        0x0,
/* 932 (procedure ITaskSchedulerService::SchRpcGetLastRunInfo) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x10),	/* method 16 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x22),	/* server buffer = 34 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 958 (parameter path) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x1d8),	/* type offset = 472 */
/* 964 (parameter last_runtime) */
        NdrFcShort(0x4112),	/* flags: must free, out, simple ref, srv size=16 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x1a4),	/* type offset = 420 */
/* 970 (parameter last_return_code) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x09,	/* FC_ULONG */
        0x0,
/* 976 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 982 (procedure ITaskSchedulerService::SchRpcGetTaskInfo) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x11),	/* method 17 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x18),	/* server buffer = 24 */
        0x46,
        0x05,	/* 5 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1008 (parameter path) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x1e4),	/* type offset = 484 */
/* 1014 (parameter flags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 1020 (parameter enabled) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x09,	/* FC_ULONG */
        0x0,
/* 1026 (parameter task_state) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x09,	/* FC_ULONG */
        0x0,
/* 1032 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 1038 (procedure ITaskSchedulerService::SchRpcGetNumberOfMissedRuns) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x12),	/* method 18 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x46,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1064 (parameter path) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x1f0),	/* type offset = 496 */
/* 1070 (parameter runs) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x09,	/* FC_ULONG */
        0x0,
/* 1076 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1082 (procedure ITaskSchedulerService::SchRpcEnableTask) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x13),	/* method 19 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1108 (parameter path) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x1f8),	/* type offset = 504 */
/* 1114 (parameter enabled) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 1120 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 6 (const WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/*  8 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 10 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 12 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 14 (const WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 16 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 18 (const WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 20 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 22 (const WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 24 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 26 (TASK_USER_CRED) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x18),	/* 24 */
        NdrFcShort(0x0),
        NdrFcShort(0x8),	/* Offset= 8 (40) */
        0x36,	/* FC_POINTER */
        0x36,	/* FC_POINTER */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 40 (const WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 42 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 44 (const WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 46 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 48 (const TASK_USER_CRED *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x29,	/* Corr desc: parameter n_creds, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x28),	/* offset = 40 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffd8),	/* Offset= -40 (26) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 70 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xffe8),	/* Offset= -24 (48) */
/* 74 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 76 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 78 (WCHAR **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (74) */
/* 82 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 84 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 86 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 88 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 90 (TASK_XML_ERROR_INFO) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x18),	/* 24 */
        NdrFcShort(0x0),
        NdrFcShort(0x8),	/* Offset= 8 (104) */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x36,	/* FC_POINTER */
        0x36,	/* FC_POINTER */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 104 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 106 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 108 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 110 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 112 (TASK_XML_ERROR_INFO *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe8),	/* Offset= -24 (90) */
/* 116 (TASK_XML_ERROR_INFO **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (112) */
/* 120 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 122 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 124 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 126 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 128 (ULONG *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 132 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 134 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 136 (WCHAR **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (132) */
/* 140 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 142 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 144 (const WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 146 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 148 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 150 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 152 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 154 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 156 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 158 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 160 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 162 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 164 (WCHAR **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (160) */
/* 168 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 170 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 172 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 176 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 180 (TASK_NAMES) */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0x2),
/* 184 (TASK_NAMES) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x29,	/* Corr desc: parameter n_names, FC_ULONG */
        0x54,	/* FC_DEREFERENCE */
        NdrFcShort(0x20),	/* offset = 32 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
/* 200 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 202 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 206 (TASK_NAMES *) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xffe4),	/* Offset= -28 (180) */
/* 210 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 212 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 214 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 218 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 222 (TASK_NAMES) */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0x2),
/* 226 (TASK_NAMES) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x29,	/* Corr desc: parameter n_names, FC_ULONG */
        0x54,	/* FC_DEREFERENCE */
        NdrFcShort(0x20),	/* offset = 32 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
/* 242 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 244 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 248 (TASK_NAMES *) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xffe4),	/* Offset= -28 (222) */
/* 252 (const WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 254 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 256 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 260 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 266 (GUID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (260) */
        0x5b,	/* FC_END */
/* 278 (GUID *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x29,	/* Corr desc: parameter n_guids, FC_ULONG */
        0x54,	/* FC_DEREFERENCE */
        NdrFcShort(0x10),	/* offset = 16 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe8),	/* Offset= -24 (266) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 294 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xffee),	/* Offset= -18 (278) */
/* 298 (GUID **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (294) */
/* 302 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 304 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 306 (WCHAR **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (302) */
/* 310 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 314 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 316 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 318 (WCHAR **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (314) */
/* 322 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 324 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 326 (WCHAR **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (322) */
/* 330 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 334 (GUID *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x29,	/* Corr desc: parameter n_instances, FC_ULONG */
        0x54,	/* FC_DEREFERENCE */
        NdrFcShort(0x28),	/* offset = 40 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffb0),	/* Offset= -80 (266) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 350 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xffee),	/* Offset= -18 (334) */
/* 354 (GUID **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (350) */
/* 358 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 362 (const WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 364 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 366 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 368 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 370 (const WCHAR **) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x29,	/* Corr desc: parameter n_args, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x8),	/* offset = 8 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x05,	/* FC_WCHAR */
        0x5c,	/* FC_PAD */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 392 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xffe8),	/* Offset= -24 (370) */
/* 396 (const WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 398 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 400 (GUID *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff78),	/* Offset= -136 (266) */
/* 404 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 406 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 408 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 410 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 412 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 414 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 416 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 418 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 420 (SYSTEMTIME) */
        0x15,	/* FC_STRUCT */
        0x1,	/* 1 */
        NdrFcShort(0x10),	/* 16 */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 434 (SYSTEMTIME *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfff0),	/* Offset= -16 (420) */
/* 438 (SYSTEMTIME *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffec),	/* Offset= -20 (420) */
/* 442 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 446 (SYSTEMTIME *) */
        0x1b,	/* FC_CARRAY */
        0x1,	/* 1 */
        NdrFcShort(0x10),	/* 16 */
        0x29,	/* Corr desc: parameter n_runtimes, FC_ULONG */
        0x54,	/* FC_DEREFERENCE */
        NdrFcShort(0x28),	/* offset = 40 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffda),	/* Offset= -38 (420) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 462 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xffee),	/* Offset= -18 (446) */
/* 466 (SYSTEMTIME **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (462) */
/* 470 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 472 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 474 (SYSTEMTIME *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffc8),	/* Offset= -56 (420) */
/* 478 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 482 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 484 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 486 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 490 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 494 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 496 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 498 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 502 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 504 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
        0x0
    }
};

