/*** Autogenerated by WIDL 9.21 from dlls/rpcrt4/tests/explicit_handle.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __explicit_handle_h__
#define __explicit_handle_h__

/* Forward declarations */

/* Headers for imported files */


#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * RPCExplicitHandle interface (v0.0)
 */
#ifndef __RPCExplicitHandle_INTERFACE_DEFINED__
#define __RPCExplicitHandle_INTERFACE_DEFINED__

extern RPC_IF_HANDLE RPCExplicitHandle_v0_0_c_ifspec;
extern RPC_IF_HANDLE s_RPCExplicitHandle_v0_0_s_ifspec;
/* client prototype */
int __cdecl add(
    handle_t hBinding,
    int a,
    int b);

/* server prototype */
int __cdecl s_add(
    handle_t hBinding,
    int a,
    int b);

/* client prototype */
int __cdecl getNum(
    int a,
    handle_t hBinding);

/* server prototype */
int __cdecl s_getNum(
    int a,
    handle_t hBinding);

/* client prototype */
void __cdecl Shutdown(
    handle_t hBinding);

/* server prototype */
void __cdecl s_Shutdown(
    handle_t hBinding);


#endif  /* __RPCExplicitHandle_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __explicit_handle_h__ */
