/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_batch(void);
extern void func_directory(void);

const struct test winetest_testlist[] =
{
    { "batch", func_batch },
    { "directory", func_directory },
    { 0, 0 }
};
