/*** Autogenerated by WIDL 9.21 from dlls/dispex/disp_ex.idl - Do not edit ***/

#define __midl_proxy
#include "objbase.h"

#ifndef __REDQ_RPCPROXY_H_VERSION__
#define __REQUIRED_RPCPROXY_H_VERSION__ 475
#endif

#define USE_STUBLESS_PROXY
#include "rpcproxy.h"
#ifndef __RPCPROXY_H_VERSION__
#error This code needs a newer version of rpcproxy.h
#endif /* __RPCPROXY_H_VERSION__ */

#include "disp_ex.h"

#define TYPE_FORMAT_STRING_SIZE 1465
#define PROC_FORMAT_STRING_SIZE 829

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

static const MIDL_STUB_DESC Object_StubDesc;

/*****************************************************************************
 * IDispatchEx interface
 */
HRESULT STDMETHODCALLTYPE IDispatchEx_RemoteInvokeEx_Proxy(
    IDispatchEx* This,
    DISPID id,
    LCID lcid,
    DWORD dwFlags,
    DISPPARAMS *pdp,
    VARIANT *pvarRes,
    EXCEPINFO *pei,
    IServiceProvider *pspCaller,
    UINT cvarRefArg,
    UINT *rgiRefArg,
    VARIANT *rgvarRefArg)
{
    CLIENT_CALL_RETURN _RetVal;

    _RetVal = NdrClientCall2( &Object_StubDesc,
                              &__MIDL_ProcFormatString.Format[50],
                              This,
                              id,
                              lcid,
                              dwFlags,
                              pdp,
                              pvarRes,
                              pei,
                              pspCaller,
                              cvarRefArg,
                              rgiRefArg,
                              rgvarRefArg );
    return (HRESULT)_RetVal.Simple;
}

void __RPC_API IDispatchEx_RemoteInvokeEx_Thunk( PMIDL_STUB_MESSAGE pStubMsg )
{
    struct _PARAM_STRUCT
    {
        IDispatchEx *This;
        DISPID DECLSPEC_ALIGN(8) id;
        LCID DECLSPEC_ALIGN(8) lcid;
        DWORD DECLSPEC_ALIGN(8) dwFlags;
        DISPPARAMS *pdp;
        VARIANT *pvarRes;
        EXCEPINFO *pei;
        IServiceProvider *pspCaller;
        UINT DECLSPEC_ALIGN(8) cvarRefArg;
        UINT *rgiRefArg;
        VARIANT *rgvarRefArg;
        HRESULT DECLSPEC_ALIGN(8) _RetVal;
    } *pParamStruct = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pParamStruct->_RetVal = IDispatchEx_InvokeEx_Stub( pParamStruct->This,
        pParamStruct->id,
        pParamStruct->lcid,
        pParamStruct->dwFlags,
        pParamStruct->pdp,
        pParamStruct->pvarRes,
        pParamStruct->pei,
        pParamStruct->pspCaller,
        pParamStruct->cvarRefArg,
        pParamStruct->rgiRefArg,
        pParamStruct->rgvarRefArg );
}

static const unsigned short IDispatchEx_FormatStringOffsetTable[] =
{
    (unsigned short)-1,  /* IDispatch::GetTypeInfoCount */
    (unsigned short)-1,  /* IDispatch::GetTypeInfo */
    (unsigned short)-1,  /* IDispatch::GetIDsOfNames */
    (unsigned short)-1,  /* IDispatch::RemoteInvoke */
    0,  /* IDispatchEx::GetDispID */
    50,  /* IDispatchEx::RemoteInvokeEx */
    142,  /* IDispatchEx::DeleteMemberByName */
    186,  /* IDispatchEx::DeleteMemberByDispID */
    224,  /* IDispatchEx::GetMemberProperties */
    274,  /* IDispatchEx::GetMemberName */
    318,  /* IDispatchEx::GetNextDispID */
    368,  /* IDispatchEx::GetNameSpaceParent */
};

static const MIDL_STUBLESS_PROXY_INFO IDispatchEx_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IDispatchEx_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(15) _IDispatchExProxyVtbl =
{
    {
        &IDispatchEx_ProxyInfo,
        &IID_IDispatchEx,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        0,  /* IDispatch::GetTypeInfoCount */
        0,  /* IDispatch::GetTypeInfo */
        0,  /* IDispatch::GetIDsOfNames */
        0,  /* IDispatch::Invoke */
        (void *)-1,  /* IDispatchEx::GetDispID */
        IDispatchEx_InvokeEx_Proxy,
        (void *)-1,  /* IDispatchEx::DeleteMemberByName */
        (void *)-1,  /* IDispatchEx::DeleteMemberByDispID */
        (void *)-1,  /* IDispatchEx::GetMemberProperties */
        (void *)-1,  /* IDispatchEx::GetMemberName */
        (void *)-1,  /* IDispatchEx::GetNextDispID */
        (void *)-1,  /* IDispatchEx::GetNameSpaceParent */
    }
};

static const STUB_THUNK IDispatchEx_StubThunkTable[] =
{
    0, /* IDispatch::GetTypeInfoCount */
    0, /* IDispatch::GetTypeInfo */
    0, /* IDispatch::GetIDsOfNames */
    0, /* IDispatch::Invoke */
    0, /* IDispatchEx::GetDispID */
    IDispatchEx_RemoteInvokeEx_Thunk,
    0, /* IDispatchEx::DeleteMemberByName */
    0, /* IDispatchEx::DeleteMemberByDispID */
    0, /* IDispatchEx::GetMemberProperties */
    0, /* IDispatchEx::GetMemberName */
    0, /* IDispatchEx::GetNextDispID */
    0, /* IDispatchEx::GetNameSpaceParent */
};

static const MIDL_SERVER_INFO IDispatchEx_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IDispatchEx_FormatStringOffsetTable[-3],
    &IDispatchEx_StubThunkTable[-3],
    0,
    0,
    0
};

static const PRPC_STUB_FUNCTION IDispatchEx_table[] =
{
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2,
    (PRPC_STUB_FUNCTION)NdrStubCall2
};

static CInterfaceStubVtbl _IDispatchExStubVtbl =
{
    {
        &IID_IDispatchEx,
        &IDispatchEx_ServerInfo,
        15,
        &IDispatchEx_table[-3]
    },
    {
        CStdStubBuffer_DELEGATING_METHODS
    }
};

/*****************************************************************************
 * IDispError interface
 */
static const unsigned short IDispError_FormatStringOffsetTable[] =
{
    406,  /* IDispError::QueryErrorInfo */
    450,  /* IDispError::GetNext */
    488,  /* IDispError::GetHresult */
    526,  /* IDispError::GetSource */
    564,  /* IDispError::GetHelpInfo */
    608,  /* IDispError::GetDescription */
};

static const MIDL_STUBLESS_PROXY_INFO IDispError_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IDispError_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(9) _IDispErrorProxyVtbl =
{
    {
        &IDispError_ProxyInfo,
        &IID_IDispError,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IDispError::QueryErrorInfo */
        (void *)-1,  /* IDispError::GetNext */
        (void *)-1,  /* IDispError::GetHresult */
        (void *)-1,  /* IDispError::GetSource */
        (void *)-1,  /* IDispError::GetHelpInfo */
        (void *)-1,  /* IDispError::GetDescription */
    }
};

static const MIDL_SERVER_INFO IDispError_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IDispError_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IDispErrorStubVtbl =
{
    {
        &IID_IDispError,
        &IDispError_ServerInfo,
        9,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IVariantChangeType interface
 */
static const unsigned short IVariantChangeType_FormatStringOffsetTable[] =
{
    646,  /* IVariantChangeType::ChangeType */
};

static const MIDL_STUBLESS_PROXY_INFO IVariantChangeType_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IVariantChangeType_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(4) _IVariantChangeTypeProxyVtbl =
{
    {
        &IVariantChangeType_ProxyInfo,
        &IID_IVariantChangeType,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IVariantChangeType::ChangeType */
    }
};

static const MIDL_SERVER_INFO IVariantChangeType_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IVariantChangeType_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IVariantChangeTypeStubVtbl =
{
    {
        &IID_IVariantChangeType,
        &IVariantChangeType_ServerInfo,
        4,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IObjectIdentity interface
 */
static const unsigned short IObjectIdentity_FormatStringOffsetTable[] =
{
    702,  /* IObjectIdentity::IsEqualObject */
};

static const MIDL_STUBLESS_PROXY_INFO IObjectIdentity_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IObjectIdentity_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(4) _IObjectIdentityProxyVtbl =
{
    {
        &IObjectIdentity_ProxyInfo,
        &IID_IObjectIdentity,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IObjectIdentity::IsEqualObject */
    }
};

static const MIDL_SERVER_INFO IObjectIdentity_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IObjectIdentity_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IObjectIdentityStubVtbl =
{
    {
        &IID_IObjectIdentity,
        &IObjectIdentity_ServerInfo,
        4,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * ICanHandleException interface
 */
static const unsigned short ICanHandleException_FormatStringOffsetTable[] =
{
    740,  /* ICanHandleException::CanHandleException */
};

static const MIDL_STUBLESS_PROXY_INFO ICanHandleException_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &ICanHandleException_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(4) _ICanHandleExceptionProxyVtbl =
{
    {
        &ICanHandleException_ProxyInfo,
        &IID_ICanHandleException,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* ICanHandleException::CanHandleException */
    }
};

static const MIDL_SERVER_INFO ICanHandleException_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &ICanHandleException_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _ICanHandleExceptionStubVtbl =
{
    {
        &IID_ICanHandleException,
        &ICanHandleException_ServerInfo,
        4,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IProvideRuntimeContext interface
 */
static const unsigned short IProvideRuntimeContext_FormatStringOffsetTable[] =
{
    784,  /* IProvideRuntimeContext::GetCurrentSourceContext */
};

static const MIDL_STUBLESS_PROXY_INFO IProvideRuntimeContext_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IProvideRuntimeContext_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(4) _IProvideRuntimeContextProxyVtbl =
{
    {
        &IProvideRuntimeContext_ProxyInfo,
        &IID_IProvideRuntimeContext,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IProvideRuntimeContext::GetCurrentSourceContext */
    }
};

static const MIDL_SERVER_INFO IProvideRuntimeContext_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IProvideRuntimeContext_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IProvideRuntimeContextStubVtbl =
{
    {
        &IID_IProvideRuntimeContext,
        &IProvideRuntimeContext_ServerInfo,
        4,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

static const USER_MARSHAL_ROUTINE_QUADRUPLE UserMarshalRoutines[] =
{
    {
        (USER_MARSHAL_SIZING_ROUTINE)BSTR_UserSize,
        (USER_MARSHAL_MARSHALLING_ROUTINE)BSTR_UserMarshal,
        (USER_MARSHAL_UNMARSHALLING_ROUTINE)BSTR_UserUnmarshal,
        (USER_MARSHAL_FREEING_ROUTINE)BSTR_UserFree
    },
    {
        (USER_MARSHAL_SIZING_ROUTINE)VARIANT_UserSize,
        (USER_MARSHAL_MARSHALLING_ROUTINE)VARIANT_UserMarshal,
        (USER_MARSHAL_UNMARSHALLING_ROUTINE)VARIANT_UserUnmarshal,
        (USER_MARSHAL_FREEING_ROUTINE)VARIANT_UserFree
    }
};

static const MIDL_STUB_DESC Object_StubDesc =
{
    0,
    NdrOleAllocate,
    NdrOleFree,
    {0}, 0, 0, 0, 0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    UserMarshalRoutines,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};

#if !defined(__RPC_WIN64__)
#error Invalid build platform for this proxy.
#endif

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure IDispatchEx::GetDispID) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x7),	/* method 7 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 26 (parameter bstrName) */
        NdrFcShort(0x8b),	/* flags: must size, must free, in, by value */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x1c),	/* type offset = 28 */
/* 32 (parameter grfdex) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 38 (parameter pid) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 44 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 50 (procedure IDispatchEx::RemoteInvokeEx) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x8),	/* method 8 */
        NdrFcShort(0x60),	/* stack size = 96 */
        NdrFcShort(0x20),	/* client buffer = 32 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x0b,	/* 11 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 76 (parameter id) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 82 (parameter lcid) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 88 (parameter dwFlags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 94 (parameter pdp) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x480),	/* type offset = 1152 */
/* 100 (parameter pvarRes) */
        NdrFcShort(0x6113),	/* flags: must size, must free, out, simple ref, srv size=24 */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0x49a),	/* type offset = 1178 */
/* 106 (parameter pei) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x30),	/* stack offset = 48 */
        NdrFcShort(0x4b2),	/* type offset = 1202 */
/* 112 (parameter pspCaller) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x38),	/* stack offset = 56 */
        NdrFcShort(0x4d4),	/* type offset = 1236 */
/* 118 (parameter cvarRefArg) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x40),	/* stack offset = 64 */
        0x08,	/* FC_LONG */
        0x0,
/* 124 (parameter rgiRefArg) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x48),	/* stack offset = 72 */
        NdrFcShort(0x4e6),	/* type offset = 1254 */
/* 130 (parameter rgvarRefArg) */
        NdrFcShort(0x11b),	/* flags: must size, must free, in, out, simple ref */
        NdrFcShort(0x50),	/* stack offset = 80 */
        NdrFcShort(0x4f6),	/* type offset = 1270 */
/* 136 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x58),	/* stack offset = 88 */
        0x08,	/* FC_LONG */
        0x0,
/* 142 (procedure IDispatchEx::DeleteMemberByName) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x9),	/* method 9 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 168 (parameter bstrName) */
        NdrFcShort(0x8b),	/* flags: must size, must free, in, by value */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x510),	/* type offset = 1296 */
/* 174 (parameter grfdex) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 180 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 186 (procedure IDispatchEx::DeleteMemberByDispID) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xa),	/* method 10 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 212 (parameter id) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 218 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 224 (procedure IDispatchEx::GetMemberProperties) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xb),	/* method 11 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x44,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 250 (parameter id) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 256 (parameter grfdexFetch) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 262 (parameter pgrfdex) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x09,	/* FC_ULONG */
        0x0,
/* 268 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 274 (procedure IDispatchEx::GetMemberName) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xc),	/* method 12 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 300 (parameter id) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 306 (parameter pbstrName) */
        NdrFcShort(0x2113),	/* flags: must size, must free, out, simple ref, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x4a8),	/* type offset = 1192 */
/* 312 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 318 (procedure IDispatchEx::GetNextDispID) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xd),	/* method 13 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x44,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 344 (parameter grfdex) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 350 (parameter id) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 356 (parameter pid) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 362 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 368 (procedure IDispatchEx::GetNameSpaceParent) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xe),	/* method 14 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 394 (parameter ppunk) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x538),	/* type offset = 1336 */
/* 400 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 406 (procedure IDispError::QueryErrorInfo) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x14),	/* client buffer = 20 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 432 (parameter guidErrorType) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x542),	/* type offset = 1346 */
/* 438 (parameter ppde) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x560),	/* type offset = 1376 */
/* 444 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 450 (procedure IDispError::GetNext) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 476 (parameter ppde) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x576),	/* type offset = 1398 */
/* 482 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 488 (procedure IDispError::GetHresult) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x44,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 514 (parameter phr) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 520 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 526 (procedure IDispError::GetSource) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 552 (parameter pbstrSource) */
        NdrFcShort(0x2113),	/* flags: must size, must free, out, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x4a8),	/* type offset = 1192 */
/* 558 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 564 (procedure IDispError::GetHelpInfo) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x7),	/* method 7 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x45,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 590 (parameter pbstrFileName) */
        NdrFcShort(0x2113),	/* flags: must size, must free, out, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x4a8),	/* type offset = 1192 */
/* 596 (parameter pdwContext) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x09,	/* FC_ULONG */
        0x0,
/* 602 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 608 (procedure IDispError::GetDescription) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x8),	/* method 8 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 634 (parameter pbstrDescription) */
        NdrFcShort(0x2113),	/* flags: must size, must free, out, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x4a8),	/* type offset = 1192 */
/* 640 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 646 (procedure IVariantChangeType::ChangeType) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x30),	/* stack size = 48 */
        NdrFcShort(0xe),	/* client buffer = 14 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x05,	/* 5 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 672 (parameter pvarDst) */
        NdrFcShort(0x1b),	/* flags: must size, must free, in, out */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x58e),	/* type offset = 1422 */
/* 678 (parameter pvarSrc) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x592),	/* type offset = 1426 */
/* 684 (parameter lcid) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 690 (parameter vtNew) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x06,	/* FC_SHORT */
        0x0,
/* 696 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x28),	/* stack offset = 40 */
        0x08,	/* FC_LONG */
        0x0,
/* 702 (procedure IObjectIdentity::IsEqualObject) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 728 (parameter punk) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x596),	/* type offset = 1430 */
/* 734 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 740 (procedure ICanHandleException::CanHandleException) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 766 (parameter pExcepInfo) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x4b2),	/* type offset = 1202 */
/* 772 (parameter pvar) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x49a),	/* type offset = 1178 */
/* 778 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 784 (procedure IProvideRuntimeContext::GetCurrentSourceContext) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x1e),	/* server buffer = 30 */
        0x44,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 810 (parameter pdwContext) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0xb9,	/* FC_UINT3264 */
        0x0,
/* 816 (parameter pfExecutingGlobalCode) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x06,	/* FC_SHORT */
        0x0,
/* 822 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (unsigned short[]) */
        0x1b,	/* FC_CARRAY */
        0x1,	/* 1 */
        NdrFcShort(0x2),	/* 2 */
        0x9,	/* Corr desc: field clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0xfffc),	/* offset = -4 */
        NdrFcShort(0x1),
        0x06,	/* FC_SHORT */
        0x5b,	/* FC_END */
/* 14 (FLAGGED_WORD_BLOB) */
        0x17,	/* FC_CSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0xfff0),	/* Offset= -16 (2) */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 24 (wireBSTR) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfff4),	/* Offset= -12 (14) */
/* 28 (BSTR) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x0),	/* Function offset= 0 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xfff4),	/* Offset= -12 (24) */
/* 38 (DISPID *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 42 (wireBSTR) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe2),	/* Offset= -30 (14) */
/* 46 (CY) */
        0x15,	/* FC_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x8),	/* 8 */
        0x0b,	/* FC_HYPER */
        0x5b,	/* FC_END */
/* 52 (DECIMAL) */
        0x15,	/* FC_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x10),	/* 16 */
        0x06,	/* FC_SHORT */
        0x01,	/* FC_BYTE */
        0x01,	/* FC_BYTE */
        0x08,	/* FC_LONG */
        0x0b,	/* FC_HYPER */
        0x5b,	/* FC_END */
/* 62 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 80 (IDispatch *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00020400),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 98 (wireBSTR *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xff9a),	/* Offset= -102 (14) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 120 (SAFEARR_BSTR) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (132) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 132 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffdc),	/* Offset= -36 (98) */
/* 136 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 154 (IUnknown **) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffdc),	/* Offset= -36 (136) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 176 (SAFEARR_UNKNOWN) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (188) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 188 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffdc),	/* Offset= -36 (154) */
/* 192 (IDispatch *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00020400),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 210 (IDispatch **) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffdc),	/* Offset= -36 (192) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 232 (SAFEARR_DISPATCH) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (244) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 244 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffdc),	/* Offset= -36 (210) */
/* 248 (wireVARIANT *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0x332),	/* Offset= 818 (1084) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 270 (SAFEARR_VARIANT) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (282) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 282 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffdc),	/* Offset= -36 (248) */
/* 286 (IRecordInfo *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x0000002f),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 304 (byte *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x19,	/* Corr desc: field pointer clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x4),	/* offset = 4 */
        NdrFcShort(0x0),
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 316 (struct _wireBRECORD) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x18),	/* 24 */
        NdrFcShort(0x0),
        NdrFcShort(0xa),	/* Offset= 10 (332) */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffd6),	/* Offset= -42 (286) */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 332 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe2),	/* Offset= -30 (304) */
/* 336 (wireBRECORD *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffda),	/* Offset= -38 (316) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 358 (SAFEARR_BRECORD) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (370) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 370 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffdc),	/* Offset= -36 (336) */
/* 374 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 392 (IUnknown **) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffdc),	/* Offset= -36 (374) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 414 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 420 (IID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (414) */
        0x5b,	/* FC_END */
/* 432 (SAFEARR_HAVEIID) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x20),	/* 32 */
        NdrFcShort(0x0),
        NdrFcShort(0xa),	/* Offset= 10 (448) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe7),	/* Offset= -25 (420) */
        0x5b,	/* FC_END */
/* 448 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffc6),	/* Offset= -58 (392) */
/* 452 (byte *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x19,	/* Corr desc: field pointer clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 464 (BYTE_SIZEDARR) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (476) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 476 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe6),	/* Offset= -26 (452) */
/* 480 (unsigned short *) */
        0x1b,	/* FC_CARRAY */
        0x1,	/* 1 */
        NdrFcShort(0x2),	/* 2 */
        0x19,	/* Corr desc: field pointer clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        0x06,	/* FC_SHORT */
        0x5b,	/* FC_END */
/* 492 (WORD_SIZEDARR) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (504) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 504 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe6),	/* Offset= -26 (480) */
/* 508 (ULONG *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x19,	/* Corr desc: field pointer clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 520 (DWORD_SIZEDARR) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (532) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 532 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe6),	/* Offset= -26 (508) */
/* 536 (hyper *) */
        0x1b,	/* FC_CARRAY */
        0x7,	/* 7 */
        NdrFcShort(0x8),	/* 8 */
        0x19,	/* Corr desc: field pointer clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        0x0b,	/* FC_HYPER */
        0x5b,	/* FC_END */
/* 548 (HYPER_SIZEDARR) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (560) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 560 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe6),	/* Offset= -26 (536) */
/* 564 (SAFEARRAYUNION) */
        0x2a,	/* FC_ENCAPSULATED_UNION */
        0x89,	/* Switch type= FC_ULONG */
        NdrFcShort(0x20),	/* 32 */
        NdrFcShort(0xa),	/* 10 */
        NdrFcLong(0x8),	/* 8 */
        NdrFcShort(0xfe3a),	/* Offset= -454 (120) */
        NdrFcLong(0xd),	/* 13 */
        NdrFcShort(0xfe6c),	/* Offset= -404 (176) */
        NdrFcLong(0x9),	/* 9 */
        NdrFcShort(0xfe9e),	/* Offset= -354 (232) */
        NdrFcLong(0xc),	/* 12 */
        NdrFcShort(0xfebe),	/* Offset= -322 (270) */
        NdrFcLong(0x24),	/* 36 */
        NdrFcShort(0xff10),	/* Offset= -240 (358) */
        NdrFcLong(0x800d),	/* 32781 */
        NdrFcShort(0xff54),	/* Offset= -172 (432) */
        NdrFcLong(0x10),	/* 16 */
        NdrFcShort(0xff6e),	/* Offset= -146 (464) */
        NdrFcLong(0x2),	/* 2 */
        NdrFcShort(0xff84),	/* Offset= -124 (492) */
        NdrFcLong(0x3),	/* 3 */
        NdrFcShort(0xff9a),	/* Offset= -102 (520) */
        NdrFcLong(0x14),	/* 20 */
        NdrFcShort(0xffb0),	/* Offset= -80 (548) */
        NdrFcShort(0xffff),
/* 632 (SAFEARRAYBOUND) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 640 (SAFEARRAYBOUND[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x7,	/* Corr desc: field cDims, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0xffc8),	/* offset = -56 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffec),	/* Offset= -20 (632) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 656 (struct _wireSAFEARRAY) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x38),	/* 56 */
        NdrFcShort(0xffec),	/* Offset= -20 (640) */
        NdrFcShort(0x0),	/* Offset= 0 (662) */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xff95),	/* Offset= -107 (564) */
        0x5b,	/* FC_END */
/* 674 (wireSAFEARRAY) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffec),	/* Offset= -20 (656) */
/* 678 (signed char *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x02,	/* FC_CHAR */
        0x5c,	/* FC_PAD */
/* 682 (USHORT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x07,	/* FC_USHORT */
        0x5c,	/* FC_PAD */
/* 686 (ULONG *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 690 (INT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 694 (UINT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 698 (BYTE *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x01,	/* FC_BYTE */
        0x5c,	/* FC_PAD */
/* 702 (SHORT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x06,	/* FC_SHORT */
        0x5c,	/* FC_PAD */
/* 706 (LONG *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 710 (FLOAT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x0a,	/* FC_FLOAT */
        0x5c,	/* FC_PAD */
/* 714 (DOUBLE *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x0c,	/* FC_DOUBLE */
        0x5c,	/* FC_PAD */
/* 718 (VARIANT_BOOL *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x06,	/* FC_SHORT */
        0x5c,	/* FC_PAD */
/* 722 (SCODE *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 726 (DATE *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x0c,	/* FC_DOUBLE */
        0x5c,	/* FC_PAD */
/* 730 (wireBSTR) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfd32),	/* Offset= -718 (14) */
/* 734 (wireBSTR *) */
        0x12, 0x10,		/* FC_UP [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (730) */
/* 738 (wireVARIANT) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0x158),	/* Offset= 344 (1084) */
/* 742 (wireVARIANT *) */
        0x12, 0x10,		/* FC_UP [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (738) */
/* 746 (CY *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfd42),	/* Offset= -702 (46) */
/* 750 (DECIMAL *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfd44),	/* Offset= -700 (52) */
/* 754 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 772 (IUnknown **) */
        0x12, 0x10,		/* FC_UP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (754) */
/* 776 (IDispatch *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00020400),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 794 (IDispatch **) */
        0x12, 0x10,		/* FC_UP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (776) */
/* 798 (wireSAFEARRAY) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xff70),	/* Offset= -144 (656) */
/* 802 (wireSAFEARRAY *) */
        0x12, 0x10,		/* FC_UP [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (798) */
/* 806 (wireBRECORD) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfe14),	/* Offset= -492 (316) */
/* 810 (union ) */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x2b),	/* 43 */
        NdrFcLong(0x0),	/* 0 */
        NdrFcShort(0x0),	/* No type */
        NdrFcLong(0x1),	/* 1 */
        NdrFcShort(0x0),	/* No type */
        NdrFcLong(0x10),	/* 16 */
        NdrFcShort(0x8002),	/* Simple arm type: FC_CHAR */
        NdrFcLong(0x12),	/* 18 */
        NdrFcShort(0x8007),	/* Simple arm type: FC_USHORT */
        NdrFcLong(0x13),	/* 19 */
        NdrFcShort(0x8009),	/* Simple arm type: FC_ULONG */
        NdrFcLong(0x16),	/* 22 */
        NdrFcShort(0x8008),	/* Simple arm type: FC_LONG */
        NdrFcLong(0x17),	/* 23 */
        NdrFcShort(0x8009),	/* Simple arm type: FC_ULONG */
        NdrFcLong(0x11),	/* 17 */
        NdrFcShort(0x8001),	/* Simple arm type: FC_BYTE */
        NdrFcLong(0x2),	/* 2 */
        NdrFcShort(0x8006),	/* Simple arm type: FC_SHORT */
        NdrFcLong(0x3),	/* 3 */
        NdrFcShort(0x8008),	/* Simple arm type: FC_LONG */
        NdrFcLong(0x4),	/* 4 */
        NdrFcShort(0x800a),	/* Simple arm type: FC_FLOAT */
        NdrFcLong(0x5),	/* 5 */
        NdrFcShort(0x800c),	/* Simple arm type: FC_DOUBLE */
        NdrFcLong(0xb),	/* 11 */
        NdrFcShort(0x8006),	/* Simple arm type: FC_SHORT */
        NdrFcLong(0xa),	/* 10 */
        NdrFcShort(0x8008),	/* Simple arm type: FC_LONG */
        NdrFcLong(0x7),	/* 7 */
        NdrFcShort(0x800c),	/* Simple arm type: FC_DOUBLE */
        NdrFcLong(0x8),	/* 8 */
        NdrFcShort(0xff4e),	/* Offset= -178 (730) */
        NdrFcLong(0x6),	/* 6 */
        NdrFcShort(0xfc9c),	/* Offset= -868 (46) */
        NdrFcLong(0xe),	/* 14 */
        NdrFcShort(0xfc9c),	/* Offset= -868 (52) */
        NdrFcLong(0xd),	/* 13 */
        NdrFcShort(0xfca0),	/* Offset= -864 (62) */
        NdrFcLong(0x9),	/* 9 */
        NdrFcShort(0xfcac),	/* Offset= -852 (80) */
        NdrFcLong(0x2000),	/* 8192 */
        NdrFcShort(0xff74),	/* Offset= -140 (798) */
        NdrFcLong(0x4010),	/* 16400 */
        NdrFcShort(0xfef6),	/* Offset= -266 (678) */
        NdrFcLong(0x4012),	/* 16402 */
        NdrFcShort(0xfef4),	/* Offset= -268 (682) */
        NdrFcLong(0x4013),	/* 16403 */
        NdrFcShort(0xfef2),	/* Offset= -270 (686) */
        NdrFcLong(0x4016),	/* 16406 */
        NdrFcShort(0xfef0),	/* Offset= -272 (690) */
        NdrFcLong(0x4017),	/* 16407 */
        NdrFcShort(0xfeee),	/* Offset= -274 (694) */
        NdrFcLong(0x4011),	/* 16401 */
        NdrFcShort(0xfeec),	/* Offset= -276 (698) */
        NdrFcLong(0x4002),	/* 16386 */
        NdrFcShort(0xfeea),	/* Offset= -278 (702) */
        NdrFcLong(0x4003),	/* 16387 */
        NdrFcShort(0xfee8),	/* Offset= -280 (706) */
        NdrFcLong(0x4004),	/* 16388 */
        NdrFcShort(0xfee6),	/* Offset= -282 (710) */
        NdrFcLong(0x4005),	/* 16389 */
        NdrFcShort(0xfee4),	/* Offset= -284 (714) */
        NdrFcLong(0x400b),	/* 16395 */
        NdrFcShort(0xfee2),	/* Offset= -286 (718) */
        NdrFcLong(0x400a),	/* 16394 */
        NdrFcShort(0xfee0),	/* Offset= -288 (722) */
        NdrFcLong(0x4007),	/* 16391 */
        NdrFcShort(0xfede),	/* Offset= -290 (726) */
        NdrFcLong(0x4008),	/* 16392 */
        NdrFcShort(0xfee0),	/* Offset= -288 (734) */
        NdrFcLong(0x400c),	/* 16396 */
        NdrFcShort(0xfee2),	/* Offset= -286 (742) */
        NdrFcLong(0x4006),	/* 16390 */
        NdrFcShort(0xfee0),	/* Offset= -288 (746) */
        NdrFcLong(0x400e),	/* 16398 */
        NdrFcShort(0xfede),	/* Offset= -290 (750) */
        NdrFcLong(0x400d),	/* 16397 */
        NdrFcShort(0xfeee),	/* Offset= -274 (772) */
        NdrFcLong(0x4009),	/* 16393 */
        NdrFcShort(0xfefe),	/* Offset= -258 (794) */
        NdrFcLong(0x6000),	/* 24576 */
        NdrFcShort(0xff00),	/* Offset= -256 (802) */
        NdrFcLong(0x24),	/* 36 */
        NdrFcShort(0xfefe),	/* Offset= -258 (806) */
        NdrFcLong(0x4024),	/* 16420 */
        NdrFcShort(0xfef8),	/* Offset= -264 (806) */
        NdrFcShort(0xffff),
/* 1074 */
        0x2b,	/* FC_NON_ENCAPSULATED_UNION */
        0x7,	/* FC_USHORT */
        0x7,	/* Corr desc: field vt, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0xfff8),	/* offset = -8 */
        NdrFcShort(0x1),
        NdrFcShort(0xfef0),	/* Offset= -272 (810) */
/* 1084 (struct _wireVARIANT) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x20),	/* 32 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (1090) */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe6),	/* Offset= -26 (1074) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1104 (wireVARIANT) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffea),	/* Offset= -22 (1084) */
/* 1108 (VARIANTARG) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x1),	/* Function offset= 1 */
        NdrFcShort(0x18),	/* 24 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xfff4),	/* Offset= -12 (1104) */
/* 1118 (VARIANTARG *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x7,	/* 7 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer cArgs, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x10),	/* offset = 16 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe4),	/* Offset= -28 (1108) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1140 (DISPID *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x19,	/* Corr desc: field pointer cNamedArgs, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x14),	/* offset = 20 */
        NdrFcShort(0x0),
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 1152 (DISPPARAMS) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x18),	/* 24 */
        NdrFcShort(0x0),
        NdrFcShort(0x8),	/* Offset= 8 (1166) */
        0x36,	/* FC_POINTER */
        0x36,	/* FC_POINTER */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1166 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffce),	/* Offset= -50 (1118) */
/* 1170 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe0),	/* Offset= -32 (1140) */
/* 1174 (DISPPARAMS *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffe8),	/* Offset= -24 (1152) */
/* 1178 (VARIANT) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x1),	/* Function offset= 1 */
        NdrFcShort(0x18),	/* 24 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xffae),	/* Offset= -82 (1104) */
/* 1188 (VARIANT *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfff4),	/* Offset= -12 (1178) */
/* 1192 (BSTR) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x0),	/* Function offset= 0 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xfe2a),	/* Offset= -470 (730) */
/* 1202 (EXCEPINFO) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x40),	/* 64 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (1208) */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x40,	/* FC_STRUCTPAD4 */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe9),	/* Offset= -23 (1192) */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe5),	/* Offset= -27 (1192) */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe1),	/* Offset= -31 (1192) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0xb8,	/* FC_INT3264 */
        0xb8,	/* FC_INT3264 */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x5b,	/* FC_END */
/* 1232 (EXCEPINFO *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffe0),	/* Offset= -32 (1202) */
/* 1236 (IServiceProvider *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x6d5140c1),
        NdrFcShort(0x7436),
        NdrFcShort(0x11ce),
        0x80,
        0x34,
        0x00,
        0xaa,
        0x00,
        0x60,
        0x09,
        0xfa,

/* 1254 (UINT *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x29,	/* Corr desc: parameter cvarRefArg, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x40),	/* offset = 64 */
        NdrFcShort(0x1),
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 1266 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff2),	/* Offset= -14 (1254) */
/* 1270 (VARIANT *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x7,	/* 7 */
        NdrFcShort(0x0),	/* 0 */
        0x29,	/* Corr desc: parameter cvarRefArg, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x40),	/* offset = 64 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xff92),	/* Offset= -110 (1178) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1292 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xffe8),	/* Offset= -24 (1270) */
/* 1296 (BSTR) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x0),	/* Function offset= 0 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xfdc2),	/* Offset= -574 (730) */
/* 1306 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 1310 (BSTR *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff88),	/* Offset= -120 (1192) */
/* 1314 (DISPID *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 1318 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 1336 (IUnknown **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (1318) */
/* 1340 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 1346 (GUID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (1340) */
        0x5b,	/* FC_END */
/* 1358 (IDispError *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0xa6ef9861),
        NdrFcShort(0xc720),
        NdrFcShort(0x11d0),
        0x93,
        0x37,
        0x00,
        0xa0,
        0xc9,
        0x0d,
        0xca,
        0xa9,

/* 1376 (IDispError **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (1358) */
/* 1380 (IDispError *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0xa6ef9861),
        NdrFcShort(0xc720),
        NdrFcShort(0x11d0),
        0x93,
        0x37,
        0x00,
        0xa0,
        0xc9,
        0x0d,
        0xca,
        0xa9,

/* 1398 (IDispError **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (1380) */
/* 1402 (HRESULT *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 1406 (BSTR *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff28),	/* Offset= -216 (1192) */
/* 1410 (BSTR *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff24),	/* Offset= -220 (1192) */
/* 1414 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 1418 (BSTR *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff1c),	/* Offset= -228 (1192) */
/* 1422 (VARIANT *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xff0a),	/* Offset= -246 (1178) */
/* 1426 (VARIANT *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xff06),	/* Offset= -250 (1178) */
/* 1430 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 1448 (EXCEPINFO *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff08),	/* Offset= -248 (1202) */
/* 1452 (VARIANT *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfeec),	/* Offset= -276 (1178) */
/* 1456 (DWORD_PTR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0xb9,	/* FC_UINT3264 */
        0x5c,	/* FC_PAD */
/* 1460 (VARIANT_BOOL *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x06,	/* FC_SHORT */
        0x5c,	/* FC_PAD */
        0x0
    }
};

static const CInterfaceProxyVtbl* const _disp_ex_ProxyVtblList[] =
{
    (const CInterfaceProxyVtbl*)&_IProvideRuntimeContextProxyVtbl,
    (const CInterfaceProxyVtbl*)&_ICanHandleExceptionProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IDispatchExProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IDispErrorProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IVariantChangeTypeProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IObjectIdentityProxyVtbl,
    0
};

static const CInterfaceStubVtbl* const _disp_ex_StubVtblList[] =
{
    &_IProvideRuntimeContextStubVtbl,
    &_ICanHandleExceptionStubVtbl,
    &_IDispatchExStubVtbl,
    &_IDispErrorStubVtbl,
    &_IVariantChangeTypeStubVtbl,
    &_IObjectIdentityStubVtbl,
    0
};

static PCInterfaceName const _disp_ex_InterfaceNamesList[] =
{
    "IProvideRuntimeContext",
    "ICanHandleException",
    "IDispatchEx",
    "IDispError",
    "IVariantChangeType",
    "IObjectIdentity",
    0
};

static const IID * _disp_ex_BaseIIDList[] =
{
    0,
    0,
    &IID_IDispatch,  /* IDispatchEx */
    0,
    0,
    0,
    0
};

static int __stdcall _disp_ex_IID_Lookup(const IID* pIID, int* pIndex)
{
    int low = 0, high = 5;

    while (low <= high)
    {
        int pos = (low + high) / 2;
        int res = IID_GENERIC_CHECK_IID(_disp_ex, pIID, pos);
        if (!res) { *pIndex = pos; return 1; }
        if (res > 0) low = pos + 1;
        else high = pos - 1;
    }
    return 0;
}

const ExtendedProxyFileInfo disp_ex_ProxyFileInfo =
{
    (const PCInterfaceProxyVtblList*)_disp_ex_ProxyVtblList,
    (const PCInterfaceStubVtblList*)_disp_ex_StubVtblList,
    _disp_ex_InterfaceNamesList,
    _disp_ex_BaseIIDList,
    _disp_ex_IID_Lookup,
    6,
    2,
    0,
    0,
    0,
    0
};
