/*** Autogenerated by WIDL 9.21 from dlls/netapi32/atsvc.idl - Do not edit ***/
#include <string.h>

#include "atsvc.h"

#define TYPE_FORMAT_STRING_SIZE 135
#define PROC_FORMAT_STRING_SIZE 237

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

static const GENERIC_BINDING_ROUTINE_PAIR BindingRoutines[] =
{
    { (GENERIC_BINDING_ROUTINE)ATSVC_HANDLE_bind, (GENERIC_UNBIND_ROUTINE)ATSVC_HANDLE_unbind },
};

/*****************************************************************************
 * atsvc interface
 */

handle_t atsvc_handle;

static const RPC_CLIENT_INTERFACE atsvc___RpcClientInterface =
{
    sizeof(RPC_CLIENT_INTERFACE),
    {{0x1ff70682,0x0a51,0x30e8,{0x07,0x6d,0x74,0x0b,0xe8,0xce,0xe9,0x8b}},{1,0}},
    {{0x8a885d04,0x1ceb,0x11c9,{0x9f,0xe8,0x08,0x00,0x2b,0x10,0x48,0x60}},{2,0}},
    0,
    0,
    0,
    0,
    0,
    0,
};
RPC_IF_HANDLE atsvc_v1_0_c_ifspec = (RPC_IF_HANDLE)& atsvc___RpcClientInterface;

static const MIDL_STUB_DESC atsvc_StubDesc;

DWORD __cdecl NetrJobAdd(
    ATSVC_HANDLE ServerName,
    LPAT_INFO pAtInfo,
    LPDWORD pJobId)
{
    CLIENT_CALL_RETURN _RetVal;

    _RetVal = NdrClientCall2( &atsvc_StubDesc,
                              &__MIDL_ProcFormatString.Format[0],
                              ServerName,
                              pAtInfo,
                              pJobId );
    return (DWORD)_RetVal.Simple;
}

DWORD __cdecl NetrJobDel(
    ATSVC_HANDLE ServerName,
    DWORD MinJobId,
    DWORD MaxJobId)
{
    CLIENT_CALL_RETURN _RetVal;

    _RetVal = NdrClientCall2( &atsvc_StubDesc,
                              &__MIDL_ProcFormatString.Format[56],
                              ServerName,
                              MinJobId,
                              MaxJobId );
    return (DWORD)_RetVal.Simple;
}

DWORD __cdecl NetrJobEnum(
    ATSVC_HANDLE ServerName,
    LPAT_ENUM_CONTAINER pEnumContainer,
    DWORD PreferredMaximumLength,
    LPDWORD pTotalEntries,
    LPDWORD pResumeHandle)
{
    CLIENT_CALL_RETURN _RetVal;

    _RetVal = NdrClientCall2( &atsvc_StubDesc,
                              &__MIDL_ProcFormatString.Format[112],
                              ServerName,
                              pEnumContainer,
                              PreferredMaximumLength,
                              pTotalEntries,
                              pResumeHandle );
    return (DWORD)_RetVal.Simple;
}

DWORD __cdecl NetrJobGetInfo(
    ATSVC_HANDLE ServerName,
    DWORD JobId,
    LPAT_INFO *ppAtInfo)
{
    CLIENT_CALL_RETURN _RetVal;

    _RetVal = NdrClientCall2( &atsvc_StubDesc,
                              &__MIDL_ProcFormatString.Format[180],
                              ServerName,
                              JobId,
                              ppAtInfo );
    return (DWORD)_RetVal.Simple;
}

#if !defined(__RPC_WIN64__)
#error  Invalid build platform for this stub.
#endif

static const MIDL_STUB_DESC atsvc_StubDesc =
{
    (void *)& atsvc___RpcClientInterface,
    MIDL_user_allocate,
    MIDL_user_free,
    {
        &atsvc_handle,
    },
    0,
    BindingRoutines,
    0,
    0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};


static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure atsvc::NetrJobAdd) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x0),	/* method 0 */
        NdrFcShort(0x20),	/* stack size = 32 */
        0x31,	/* FC_BIND_GENERIC */
        0x08,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x5c,	/* FC_PAD */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 32 (parameter ServerName) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x2),	/* type offset = 2 */
/* 38 (parameter pAtInfo) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xa),	/* type offset = 10 */
/* 44 (parameter pJobId) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x09,	/* FC_ULONG */
        0x0,
/* 50 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 56 (procedure atsvc::NetrJobDel) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x1),	/* method 1 */
        NdrFcShort(0x20),	/* stack size = 32 */
        0x31,	/* FC_BIND_GENERIC */
        0x08,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x5c,	/* FC_PAD */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 88 (parameter ServerName) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x26),	/* type offset = 38 */
/* 94 (parameter MinJobId) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 100 (parameter MaxJobId) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 106 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 112 (procedure atsvc::NetrJobEnum) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x2),	/* method 2 */
        NdrFcShort(0x30),	/* stack size = 48 */
        0x31,	/* FC_BIND_GENERIC */
        0x08,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x5c,	/* FC_PAD */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x20),	/* server buffer = 32 */
        0x47,
        0x06,	/* 6 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 144 (parameter ServerName) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x2a),	/* type offset = 42 */
/* 150 (parameter pEnumContainer) */
        NdrFcShort(0x11b),	/* flags: must size, must free, in, out, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x5e),	/* type offset = 94 */
/* 156 (parameter PreferredMaximumLength) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 162 (parameter pTotalEntries) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x09,	/* FC_ULONG */
        0x0,
/* 168 (parameter pResumeHandle) */
        NdrFcShort(0x1a),	/* flags: must free, in, out */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x76),	/* type offset = 118 */
/* 174 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x28),	/* stack offset = 40 */
        0x08,	/* FC_LONG */
        0x0,
/* 180 (procedure atsvc::NetrJobGetInfo) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x20),	/* stack size = 32 */
        0x31,	/* FC_BIND_GENERIC */
        0x08,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x5c,	/* FC_PAD */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 212 (parameter ServerName) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x7a),	/* type offset = 122 */
/* 218 (parameter JobId) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 224 (parameter ppAtInfo) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x82),	/* type offset = 130 */
/* 230 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (ATSVC_HANDLE) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/*  4 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 6 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/*  8 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 10 (struct _AT_INFO) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x18),	/* 24 */
        NdrFcShort(0x0),
        NdrFcShort(0xa),	/* Offset= 10 (26) */
        0xb8,	/* FC_INT3264 */
        0x08,	/* FC_LONG */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x3e,	/* FC_STRUCTPAD2 */
        0x36,	/* FC_POINTER */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 26 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 28 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 30 (LPAT_INFO) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffea),	/* Offset= -22 (10) */
/* 34 (LPDWORD) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 38 (ATSVC_HANDLE) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 40 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 42 (ATSVC_HANDLE) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 44 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 46 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 48 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 50 (struct _AT_ENUM) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x20),	/* 32 */
        NdrFcShort(0x0),
        NdrFcShort(0xc),	/* Offset= 12 (68) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0xb8,	/* FC_INT3264 */
        0x08,	/* FC_LONG */
        0x02,	/* FC_CHAR */
        0x02,	/* FC_CHAR */
        0x3e,	/* FC_STRUCTPAD2 */
        0x36,	/* FC_POINTER */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 68 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 70 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 72 (LPAT_ENUM) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer EntriesRead, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffd8),	/* Offset= -40 (50) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 94 (struct _AT_ENUM_CONTAINER) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (106) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 106 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffdc),	/* Offset= -36 (72) */
/* 110 (LPAT_ENUM_CONTAINER) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffee),	/* Offset= -18 (94) */
/* 114 (LPDWORD) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 118 (LPDWORD) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 122 (ATSVC_HANDLE) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 124 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 126 (LPAT_INFO) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xff8a),	/* Offset= -118 (10) */
/* 130 (LPAT_INFO *) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (126) */
        0x0
    }
};

