/*** Autogenerated by WIDL 9.21 from dlls/msttsengine/ttseng_classes.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __ttseng_classes_h__
#define __ttseng_classes_h__

/* Forward declarations */

#ifndef __TTSEngineCom_FWD_DEFINED__
#define __TTSEngineCom_FWD_DEFINED__
#ifdef __cplusplus
typedef class TTSEngineCom TTSEngineCom;
#else
typedef struct TTSEngineCom TTSEngineCom;
#endif /* defined __cplusplus */
#endif /* defined __TTSEngineCom_FWD_DEFINED__ */

/* Headers for imported files */


#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * TTSEngineCom coclass
 */

DEFINE_GUID(CLSID_TTSEngineCom, 0xc64501f6, 0xe6e6, 0x451f, 0xa1,0x50, 0x25,0xd0,0x83,0x9b,0xc5,0x10);

#ifdef __cplusplus
class DECLSPEC_UUID("c64501f6-e6e6-451f-a150-25d0839bc510") TTSEngineCom;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(TTSEngineCom, 0xc64501f6, 0xe6e6, 0x451f, 0xa1,0x50, 0x25,0xd0,0x83,0x9b,0xc5,0x10)
#endif
#endif

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __ttseng_classes_h__ */
