/*** Autogenerated by WIDL 9.21 from dlls/ole32/dcom.idl - Do not edit ***/

#define __midl_proxy
#include "objbase.h"

#ifndef __REDQ_RPCPROXY_H_VERSION__
#define __REQUIRED_RPCPROXY_H_VERSION__ 475
#endif

#define USE_STUBLESS_PROXY
#include "rpcproxy.h"
#ifndef __RPCPROXY_H_VERSION__
#error This code needs a newer version of rpcproxy.h
#endif /* __RPCPROXY_H_VERSION__ */

#include "dcom.h"

#define TYPE_FORMAT_STRING_SIZE 285
#define PROC_FORMAT_STRING_SIZE 219

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

static const MIDL_STUB_DESC Object_StubDesc;

/*****************************************************************************
 * IRemUnknown interface
 */
static const unsigned short IRemUnknown_FormatStringOffsetTable[] =
{
    0,  /* IRemUnknown::RemQueryInterface */
    62,  /* IRemUnknown::RemAddRef */
    112,  /* IRemUnknown::RemRelease */
};

static const MIDL_STUBLESS_PROXY_INFO IRemUnknown_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IRemUnknown_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(6) _IRemUnknownProxyVtbl =
{
    {
        &IRemUnknown_ProxyInfo,
        &IID_IRemUnknown,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IRemUnknown::RemQueryInterface */
        (void *)-1,  /* IRemUnknown::RemAddRef */
        (void *)-1,  /* IRemUnknown::RemRelease */
    }
};

static const MIDL_SERVER_INFO IRemUnknown_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IRemUnknown_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IRemUnknownStubVtbl =
{
    {
        &IID_IRemUnknown,
        &IRemUnknown_ServerInfo,
        6,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IRemUnknown2 interface
 */
static const unsigned short IRemUnknown2_FormatStringOffsetTable[] =
{
    0,  /* IRemUnknown::RemQueryInterface */
    62,  /* IRemUnknown::RemAddRef */
    112,  /* IRemUnknown::RemRelease */
    156,  /* IRemUnknown2::RemQueryInterface2 */
};

static const MIDL_STUBLESS_PROXY_INFO IRemUnknown2_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IRemUnknown2_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(7) _IRemUnknown2ProxyVtbl =
{
    {
        &IRemUnknown2_ProxyInfo,
        &IID_IRemUnknown2,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IRemUnknown::RemQueryInterface */
        (void *)-1,  /* IRemUnknown::RemAddRef */
        (void *)-1,  /* IRemUnknown::RemRelease */
        (void *)-1,  /* IRemUnknown2::RemQueryInterface2 */
    }
};

static const MIDL_SERVER_INFO IRemUnknown2_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IRemUnknown2_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IRemUnknown2StubVtbl =
{
    {
        &IID_IRemUnknown2,
        &IRemUnknown2_ServerInfo,
        7,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

static const MIDL_STUB_DESC Object_StubDesc =
{
    0,
    NdrOleAllocate,
    NdrOleFree,
    {0}, 0, 0, 0, 0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};

#if !defined(__RPC_WIN64__)
#error Invalid build platform for this proxy.
#endif

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure IRemUnknown::RemQueryInterface) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x38),	/* stack size = 56 */
        NdrFcShort(0x22),	/* client buffer = 34 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x06,	/* 6 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 26 (parameter ripid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x8),	/* type offset = 8 */
/* 32 (parameter cRefs) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 38 (parameter cIids) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x06,	/* FC_SHORT */
        0x0,
/* 44 (parameter iids) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x2a),	/* type offset = 42 */
/* 50 (parameter ppQIResults) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0x7e),	/* type offset = 126 */
/* 56 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x30),	/* stack offset = 48 */
        0x08,	/* FC_LONG */
        0x0,
/* 62 (procedure IRemUnknown::RemAddRef) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x6),	/* client buffer = 6 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 88 (parameter cInterfaceRefs) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 94 (parameter InterfaceRefs) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x8e),	/* type offset = 142 */
/* 100 (parameter pResults) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0xa2),	/* type offset = 162 */
/* 106 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 112 (procedure IRemUnknown::RemRelease) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x6),	/* client buffer = 6 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 138 (parameter cInterfaceRefs) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 144 (parameter InterfaceRefs) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0xb2),	/* type offset = 178 */
/* 150 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 156 (procedure IRemUnknown2::RemQueryInterface2) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0x38),	/* stack size = 56 */
        NdrFcShort(0x1a),	/* client buffer = 26 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x06,	/* 6 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 182 (parameter ripid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x8),	/* type offset = 8 */
/* 188 (parameter cIids) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x06,	/* FC_SHORT */
        0x0,
/* 194 (parameter iids) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0xca),	/* type offset = 202 */
/* 200 (parameter phr) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0xde),	/* type offset = 222 */
/* 206 (parameter ppMIF) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0x102),	/* type offset = 258 */
/* 212 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x30),	/* stack offset = 48 */
        0x08,	/* FC_LONG */
        0x0,
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 8 (GUID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (2) */
        0x5b,	/* FC_END */
/* 20 (REFIPID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfff2),	/* Offset= -14 (8) */
/* 24 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 30 (IID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (24) */
        0x5b,	/* FC_END */
/* 42 (IID *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x27,	/* Corr desc: parameter cIids, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0x18),	/* offset = 24 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe8),	/* Offset= -24 (30) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 58 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xffee),	/* Offset= -18 (42) */
/* 62 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 68 (IPID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (62) */
        0x5b,	/* FC_END */
/* 80 (STDOBJREF) */
        0x15,	/* FC_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x28),	/* 40 */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x0b,	/* FC_HYPER */
        0x0b,	/* FC_HYPER */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffea),	/* Offset= -22 (68) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 94 (REMQIRESULT) */
        0x15,	/* FC_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x30),	/* 48 */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffea),	/* Offset= -22 (80) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 106 (REMQIRESULT *) */
        0x1b,	/* FC_CARRAY */
        0x7,	/* 7 */
        NdrFcShort(0x30),	/* 48 */
        0x27,	/* Corr desc: parameter cIids, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0x18),	/* offset = 24 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe8),	/* Offset= -24 (94) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 122 */
        0x13, 0x0,	/* FC_OP */
        NdrFcShort(0xffee),	/* Offset= -18 (106) */
/* 126 (REMQIRESULT **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (122) */
/* 130 (REMINTERFACEREF) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x18),	/* 24 */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffbc),	/* Offset= -68 (68) */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 142 (REMINTERFACEREF *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x18),	/* 24 */
        0x27,	/* Corr desc: parameter cInterfaceRefs, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0x8),	/* offset = 8 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe8),	/* Offset= -24 (130) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 158 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xffee),	/* Offset= -18 (142) */
/* 162 (HRESULT *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x27,	/* Corr desc: parameter cInterfaceRefs, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0x8),	/* offset = 8 */
        NdrFcShort(0x1),
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 174 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff2),	/* Offset= -14 (162) */
/* 178 (REMINTERFACEREF *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x18),	/* 24 */
        0x27,	/* Corr desc: parameter cInterfaceRefs, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0x8),	/* offset = 8 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffc4),	/* Offset= -60 (130) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 194 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xffee),	/* Offset= -18 (178) */
/* 198 (REFIPID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff40),	/* Offset= -192 (8) */
/* 202 (IID *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x27,	/* Corr desc: parameter cIids, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0x10),	/* offset = 16 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xff48),	/* Offset= -184 (30) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 218 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xffee),	/* Offset= -18 (202) */
/* 222 (HRESULT *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x27,	/* Corr desc: parameter cIids, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0x10),	/* offset = 16 */
        NdrFcShort(0x1),
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 234 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff2),	/* Offset= -14 (222) */
/* 238 (BYTE[]) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x9,	/* Corr desc: field ulCntData, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0xfffc),	/* offset = -4 */
        NdrFcShort(0x1),
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 250 (MInterfacePointer) */
        0x17,	/* FC_CSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        NdrFcShort(0xfff0),	/* Offset= -16 (238) */
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 258 (MInterfacePointer **) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x27,	/* Corr desc: parameter cIids, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0x10),	/* offset = 16 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe6),	/* Offset= -26 (250) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 280 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xffe8),	/* Offset= -24 (258) */
        0x0
    }
};

static const CInterfaceProxyVtbl* const _dcom_ProxyVtblList[] =
{
    (const CInterfaceProxyVtbl*)&_IRemUnknownProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IRemUnknown2ProxyVtbl,
    0
};

static const CInterfaceStubVtbl* const _dcom_StubVtblList[] =
{
    &_IRemUnknownStubVtbl,
    &_IRemUnknown2StubVtbl,
    0
};

static PCInterfaceName const _dcom_InterfaceNamesList[] =
{
    "IRemUnknown",
    "IRemUnknown2",
    0
};

static int __stdcall _dcom_IID_Lookup(const IID* pIID, int* pIndex)
{
    int low = 0, high = 1;

    while (low <= high)
    {
        int pos = (low + high) / 2;
        int res = IID_GENERIC_CHECK_IID(_dcom, pIID, pos);
        if (!res) { *pIndex = pos; return 1; }
        if (res > 0) low = pos + 1;
        else high = pos - 1;
    }
    return 0;
}

const ExtendedProxyFileInfo dcom_ProxyFileInfo =
{
    (const PCInterfaceProxyVtblList*)_dcom_ProxyVtblList,
    (const PCInterfaceStubVtblList*)_dcom_StubVtblList,
    _dcom_InterfaceNamesList,
    0,
    _dcom_IID_Lookup,
    2,
    2,
    0,
    0,
    0,
    0
};
