/*** Autogenerated by WIDL 9.21 from dlls/rpcrt4/tests/cstub.idl - Do not edit ***/

#define __midl_proxy
#include "objbase.h"

#ifndef __REDQ_RPCPROXY_H_VERSION__
#define __REQUIRED_RPCPROXY_H_VERSION__ 475
#endif

#define USE_STUBLESS_PROXY
#include "rpcproxy.h"
#ifndef __RPCPROXY_H_VERSION__
#error This code needs a newer version of rpcproxy.h
#endif /* __RPCPROXY_H_VERSION__ */

#include "cstub.h"

#define TYPE_FORMAT_STRING_SIZE 3
#define PROC_FORMAT_STRING_SIZE 39

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

static const MIDL_STUB_DESC Object_StubDesc;

/*****************************************************************************
 * ITest1 interface
 */
static const unsigned short ITest1_FormatStringOffsetTable[] =
{
    (unsigned short)-1,  /* IPersist::GetClassID */
    0,  /* ITest1::square */
};

static const MIDL_STUBLESS_PROXY_INFO ITest1_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &ITest1_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(5) _ITest1ProxyVtbl =
{
    {
        &ITest1_ProxyInfo,
        &IID_ITest1,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        0,  /* IPersist::GetClassID */
        (void *)-1,  /* ITest1::square */
    }
};

static const MIDL_SERVER_INFO ITest1_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &ITest1_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const PRPC_STUB_FUNCTION ITest1_table[] =
{
    STUB_FORWARDING_FUNCTION,
    (PRPC_STUB_FUNCTION)NdrStubCall2
};

static CInterfaceStubVtbl _ITest1StubVtbl =
{
    {
        &IID_ITest1,
        &ITest1_ServerInfo,
        5,
        &ITest1_table[-3]
    },
    {
        CStdStubBuffer_DELEGATING_METHODS
    }
};

static const MIDL_STUB_DESC Object_StubDesc =
{
    0,
    NdrOleAllocate,
    NdrOleFree,
    {0}, 0, 0, 0, 0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};

#if !defined(__RPC_WIN64__)
#error Invalid build platform for this proxy.
#endif

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure ITest1::square) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 26 (parameter x) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 32 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
        0x0
    }
};

static const CInterfaceProxyVtbl* const _cstub_ProxyVtblList[] =
{
    (const CInterfaceProxyVtbl*)&_ITest1ProxyVtbl,
    0
};

static const CInterfaceStubVtbl* const _cstub_StubVtblList[] =
{
    &_ITest1StubVtbl,
    0
};

static PCInterfaceName const _cstub_InterfaceNamesList[] =
{
    "ITest1",
    0
};

static const IID * _cstub_BaseIIDList[] =
{
    &IID_IPersist,  /* ITest1 */
    0
};

static int __stdcall _cstub_IID_Lookup(const IID* pIID, int* pIndex)
{
    int low = 0, high = 0;

    while (low <= high)
    {
        int pos = (low + high) / 2;
        int res = IID_GENERIC_CHECK_IID(_cstub, pIID, pos);
        if (!res) { *pIndex = pos; return 1; }
        if (res > 0) low = pos + 1;
        else high = pos - 1;
    }
    return 0;
}

const ExtendedProxyFileInfo cstub_ProxyFileInfo =
{
    (const PCInterfaceProxyVtblList*)_cstub_ProxyVtblList,
    (const PCInterfaceStubVtblList*)_cstub_StubVtblList,
    _cstub_InterfaceNamesList,
    _cstub_BaseIIDList,
    _cstub_IID_Lookup,
    1,
    2,
    0,
    0,
    0,
    0
};
