/*** Autogenerated by WIDL 9.21 from dlls/rpcrt4/tests/explicit_handle.idl - Do not edit ***/
#include <string.h>

#include "explicit_handle.h"

#define TYPE_FORMAT_STRING_SIZE 3
#define PROC_FORMAT_STRING_SIZE 121

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

/*****************************************************************************
 * RPCExplicitHandle interface
 */

static const RPC_CLIENT_INTERFACE RPCExplicitHandle___RpcClientInterface =
{
    sizeof(RPC_CLIENT_INTERFACE),
    {{0x00000000,0x4114,0x0704,{0x23,0x01,0x00,0x00,0x00,0x00,0x00,0x02}},{0,0}},
    {{0x8a885d04,0x1ceb,0x11c9,{0x9f,0xe8,0x08,0x00,0x2b,0x10,0x48,0x60}},{2,0}},
    0,
    0,
    0,
    0,
    0,
    0,
};
RPC_IF_HANDLE RPCExplicitHandle_v0_0_c_ifspec = (RPC_IF_HANDLE)& RPCExplicitHandle___RpcClientInterface;

static const MIDL_STUB_DESC RPCExplicitHandle_StubDesc;

static RPC_BINDING_HANDLE RPCExplicitHandle__MIDL_AutoBindHandle;

int __cdecl add(
    handle_t hBinding,
    int a,
    int b)
{
    CLIENT_CALL_RETURN _RetVal;

    _RetVal = NdrClientCall2( &RPCExplicitHandle_StubDesc,
                              &__MIDL_ProcFormatString.Format[0],
                              hBinding,
                              a,
                              b );
    return (int)_RetVal.Simple;
}

int __cdecl getNum(
    int a,
    handle_t hBinding)
{
    CLIENT_CALL_RETURN _RetVal;

    _RetVal = NdrClientCall2( &RPCExplicitHandle_StubDesc,
                              &__MIDL_ProcFormatString.Format[48],
                              a,
                              hBinding );
    return (int)_RetVal.Simple;
}

void __cdecl Shutdown(
    handle_t hBinding)
{
    NdrClientCall2( &RPCExplicitHandle_StubDesc,
                    &__MIDL_ProcFormatString.Format[90],
                    hBinding );
}

#if !defined(__RPC_WIN64__)
#error  Invalid build platform for this stub.
#endif

static const MIDL_STUB_DESC RPCExplicitHandle_StubDesc =
{
    (void *)& RPCExplicitHandle___RpcClientInterface,
    MIDL_user_allocate,
    MIDL_user_free,
    {
        &RPCExplicitHandle__MIDL_AutoBindHandle,
    },
    0,
    0,
    0,
    0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};


static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure RPCExplicitHandle::add) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x0),	/* method 0 */
        NdrFcShort(0x20),	/* stack size = 32 */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x00,
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 30 (parameter a) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 36 (parameter b) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 42 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 48 (procedure RPCExplicitHandle::getNum) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x1),	/* method 1 */
        NdrFcShort(0x18),	/* stack size = 24 */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x00,
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 78 (parameter a) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 84 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 90 (procedure RPCExplicitHandle::Shutdown) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x2),	/* method 2 */
        NdrFcShort(0x8),	/* stack size = 8 */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x00,
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x0),	/* server buffer = 0 */
        0x40,
        0x00,	/* 0 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
        0x0
    }
};

