/*** Autogenerated by WIDL 9.21 from dlls/wintypes/tests/wintypes_test.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __wintypes_test_h__
#define __wintypes_test_h__

/* Forward declarations */

#ifndef ____FIReference_1_HSTRING_FWD_DEFINED__
#define ____FIReference_1_HSTRING_FWD_DEFINED__
typedef interface __FIReference_1_HSTRING __FIReference_1_HSTRING;
#ifdef __cplusplus
#define __FIReference_1_HSTRING ABI::Windows::Foundation::IReference<HSTRING >
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <windows.foundation.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef ____FIReference_1_HSTRING_FWD_DEFINED__
#define ____FIReference_1_HSTRING_FWD_DEFINED__
typedef interface __FIReference_1_HSTRING __FIReference_1_HSTRING;
#ifdef __cplusplus
#define __FIReference_1_HSTRING ABI::Windows::Foundation::IReference<HSTRING >
#endif /* __cplusplus */
#endif

/*****************************************************************************
 * IReference<HSTRING > interface
 */
#ifndef ____FIReference_1_HSTRING_INTERFACE_DEFINED__
#define ____FIReference_1_HSTRING_INTERFACE_DEFINED__

DEFINE_GUID(IID___FIReference_1_HSTRING, 0xfd416dfb, 0x2a07, 0x52eb, 0xaa,0xe3, 0xdf,0xce,0x14,0x11,0x6c,0x05);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Foundation {
            template<>
            MIDL_INTERFACE("fd416dfb-2a07-52eb-aae3-dfce14116c05")
            IReference<HSTRING > : IReference_impl<HSTRING >
            {
            };
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__FIReference_1_HSTRING, 0xfd416dfb, 0x2a07, 0x52eb, 0xaa,0xe3, 0xdf,0xce,0x14,0x11,0x6c,0x05)
#endif
#else
typedef struct __FIReference_1_HSTRINGVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __FIReference_1_HSTRING *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __FIReference_1_HSTRING *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __FIReference_1_HSTRING *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __FIReference_1_HSTRING *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __FIReference_1_HSTRING *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __FIReference_1_HSTRING *This,
        TrustLevel *trustLevel);

    /*** IReference<HSTRING > methods ***/
    HRESULT (STDMETHODCALLTYPE *get_Value)(
        __FIReference_1_HSTRING *This,
        HSTRING *value);

    END_INTERFACE
} __FIReference_1_HSTRINGVtbl;

interface __FIReference_1_HSTRING {
    CONST_VTBL __FIReference_1_HSTRINGVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __FIReference_1_HSTRING_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __FIReference_1_HSTRING_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __FIReference_1_HSTRING_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __FIReference_1_HSTRING_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __FIReference_1_HSTRING_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __FIReference_1_HSTRING_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IReference<HSTRING > methods ***/
#define __FIReference_1_HSTRING_get_Value(This,value) (This)->lpVtbl->get_Value(This,value)
#else
/*** IUnknown methods ***/
static inline HRESULT __FIReference_1_HSTRING_QueryInterface(__FIReference_1_HSTRING* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __FIReference_1_HSTRING_AddRef(__FIReference_1_HSTRING* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __FIReference_1_HSTRING_Release(__FIReference_1_HSTRING* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __FIReference_1_HSTRING_GetIids(__FIReference_1_HSTRING* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __FIReference_1_HSTRING_GetRuntimeClassName(__FIReference_1_HSTRING* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __FIReference_1_HSTRING_GetTrustLevel(__FIReference_1_HSTRING* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IReference<HSTRING > methods ***/
static inline HRESULT __FIReference_1_HSTRING_get_Value(__FIReference_1_HSTRING* This,HSTRING *value) {
    return This->lpVtbl->get_Value(This,value);
}
#endif
#ifdef WIDL_using_Windows_Foundation
#define IID_IReference_HSTRING IID___FIReference_1_HSTRING
#define IReference_HSTRINGVtbl __FIReference_1_HSTRINGVtbl
#define IReference_HSTRING __FIReference_1_HSTRING
#define IReference_HSTRING_QueryInterface __FIReference_1_HSTRING_QueryInterface
#define IReference_HSTRING_AddRef __FIReference_1_HSTRING_AddRef
#define IReference_HSTRING_Release __FIReference_1_HSTRING_Release
#define IReference_HSTRING_GetIids __FIReference_1_HSTRING_GetIids
#define IReference_HSTRING_GetRuntimeClassName __FIReference_1_HSTRING_GetRuntimeClassName
#define IReference_HSTRING_GetTrustLevel __FIReference_1_HSTRING_GetTrustLevel
#define IReference_HSTRING_get_Value __FIReference_1_HSTRING_get_Value
#endif /* WIDL_using_Windows_Foundation */
#endif

#endif

#endif  /* ____FIReference_1_HSTRING_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */

ULONG           __RPC_USER HSTRING_UserSize     (ULONG *, ULONG, HSTRING *);
unsigned char * __RPC_USER HSTRING_UserMarshal  (ULONG *, unsigned char *, HSTRING *);
unsigned char * __RPC_USER HSTRING_UserUnmarshal(ULONG *, unsigned char *, HSTRING *);
void            __RPC_USER HSTRING_UserFree     (ULONG *, HSTRING *);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __wintypes_test_h__ */
