/*** Autogenerated by WIDL 9.21 from dlls/msdaps/row_server.idl - Do not edit ***/

#define __midl_proxy
#include "objbase.h"

#ifndef __REDQ_RPCPROXY_H_VERSION__
#define __REQUIRED_RPCPROXY_H_VERSION__ 475
#endif

#define USE_STUBLESS_PROXY
#include "rpcproxy.h"
#ifndef __RPCPROXY_H_VERSION__
#error This code needs a newer version of rpcproxy.h
#endif /* __RPCPROXY_H_VERSION__ */

#include "row_server.h"

#define TYPE_FORMAT_STRING_SIZE 2227
#define PROC_FORMAT_STRING_SIZE 1139

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

static const MIDL_STUB_DESC Object_StubDesc;

/*****************************************************************************
 * IWineRowServer interface
 */
static const unsigned short IWineRowServer_FormatStringOffsetTable[] =
{
    (unsigned short)-1,  /* IWineRowServer::SetInnerUnk */
    (unsigned short)-1,  /* IWineRowServer::GetMarshal */
    0,  /* IWineRowServer::GetColumns */
    50,  /* IWineRowServer::GetSourceRowset */
    100,  /* IWineRowServer::Open */
    168,  /* IWineRowServer::SetColumns */
    218,  /* IWineRowServer::AddRefRows */
    274,  /* IWineRowServer::GetData */
    330,  /* IWineRowServer::GetNextRows */
    392,  /* IWineRowServer::ReleaseRows */
    454,  /* IWineRowServer::RestartPosition */
    492,  /* IWineRowServer::Compare */
    560,  /* IWineRowServer::GetRowsAt */
    640,  /* IWineRowServer::GetRowsByBookmark */
    708,  /* IWineRowServer::Hash */
    776,  /* IWineRowServer::GetProperties */
    832,  /* IWineRowServer::GetReferencedRowset */
    882,  /* IWineRowServer::GetSpecification */
    926,  /* IWineRowServer::AddRefAccessor */
    970,  /* IWineRowServer::CreateAccessor */
    1038,  /* IWineRowServer::GetBindings */
    1094,  /* IWineRowServer::ReleaseAccessor */
};

static const MIDL_STUBLESS_PROXY_INFO IWineRowServer_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IWineRowServer_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(25) _IWineRowServerProxyVtbl =
{
    {
        &IWineRowServer_ProxyInfo,
        &IID_IWineRowServer,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        0,  /* IWineRowServer::SetInnerUnk */
        0,  /* IWineRowServer::GetMarshal */
        (void *)-1,  /* IWineRowServer::GetColumns */
        (void *)-1,  /* IWineRowServer::GetSourceRowset */
        (void *)-1,  /* IWineRowServer::Open */
        (void *)-1,  /* IWineRowServer::SetColumns */
        (void *)-1,  /* IWineRowServer::AddRefRows */
        (void *)-1,  /* IWineRowServer::GetData */
        (void *)-1,  /* IWineRowServer::GetNextRows */
        (void *)-1,  /* IWineRowServer::ReleaseRows */
        (void *)-1,  /* IWineRowServer::RestartPosition */
        (void *)-1,  /* IWineRowServer::Compare */
        (void *)-1,  /* IWineRowServer::GetRowsAt */
        (void *)-1,  /* IWineRowServer::GetRowsByBookmark */
        (void *)-1,  /* IWineRowServer::Hash */
        (void *)-1,  /* IWineRowServer::GetProperties */
        (void *)-1,  /* IWineRowServer::GetReferencedRowset */
        (void *)-1,  /* IWineRowServer::GetSpecification */
        (void *)-1,  /* IWineRowServer::AddRefAccessor */
        (void *)-1,  /* IWineRowServer::CreateAccessor */
        (void *)-1,  /* IWineRowServer::GetBindings */
        (void *)-1,  /* IWineRowServer::ReleaseAccessor */
    }
};

static const MIDL_SERVER_INFO IWineRowServer_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IWineRowServer_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IWineRowServerStubVtbl =
{
    {
        &IID_IWineRowServer,
        &IWineRowServer_ServerInfo,
        25,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

static void __RPC_USER IWineRowServer_GetColumnsExprEval_0000(PMIDL_STUB_MESSAGE pStubMsg)
{
    struct _PARAM_STRUCT
    {
        IWineRowServer *This;
        DBORDINAL num_cols;
        wine_getcolumns_in *in_data;
        wine_getcolumns_out *out_cols;
    } *pS = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pStubMsg->Offset = 0;
    pStubMsg->MaxCount = (ULONG_PTR)(ULONG)pS->num_cols;
}

static void __RPC_USER IWineRowServer_SetColumnsExprEval_0001(PMIDL_STUB_MESSAGE pStubMsg)
{
    struct _PARAM_STRUCT
    {
        IWineRowServer *This;
        DBORDINAL num_cols;
        wine_setcolumns_in *in_data;
        DBSTATUS *status;
    } *pS = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pStubMsg->Offset = 0;
    pStubMsg->MaxCount = (ULONG_PTR)(ULONG)pS->num_cols;
}

static void __RPC_USER IWineRowServer_AddRefRowsExprEval_0002(PMIDL_STUB_MESSAGE pStubMsg)
{
    struct _PARAM_STRUCT
    {
        IWineRowServer *This;
        DBCOUNTITEM cRows;
        const HROW *rghRows;
        DBREFCOUNT *rgRefCounts;
        DBROWSTATUS *rgRowStatus;
    } *pS = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pStubMsg->Offset = 0;
    pStubMsg->MaxCount = (ULONG_PTR)(ULONG)pS->cRows;
}

static void __RPC_USER IWineRowServer_GetNextRowsExprEval_0003(PMIDL_STUB_MESSAGE pStubMsg)
{
    struct _PARAM_STRUCT
    {
        IWineRowServer *This;
        HCHAPTER hReserved;
        DBROWOFFSET lRowsOffset;
        DBROWCOUNT cRows;
        DBCOUNTITEM *pcRowObtained;
        HROW **prghRows;
    } *pS = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pStubMsg->Offset = 0;
    pStubMsg->MaxCount = (ULONG_PTR)(ULONG)pS->cRows;
}

static void __RPC_USER IWineRowServer_ReleaseRowsExprEval_0004(PMIDL_STUB_MESSAGE pStubMsg)
{
    struct _PARAM_STRUCT
    {
        IWineRowServer *This;
        DBCOUNTITEM cRows;
        const HROW *rghRows;
        DBROWOPTIONS *rgRowOptions;
        DBREFCOUNT *rgRefCounts;
        DBROWSTATUS *rgRowStatus;
    } *pS = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pStubMsg->Offset = 0;
    pStubMsg->MaxCount = (ULONG_PTR)(ULONG)pS->cRows;
}

static void __RPC_USER IWineRowServer_CompareExprEval_0005(PMIDL_STUB_MESSAGE pStubMsg)
{
    struct _PARAM_STRUCT
    {
        IWineRowServer *This;
        HCHAPTER hReserved;
        DBBKMARK cbBookmark1;
        const BYTE *pBookmark1;
        DBBKMARK cbBookmark2;
        const BYTE *pBookmark2;
        DBCOMPARE *pComparison;
    } *pS = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pStubMsg->Offset = 0;
    pStubMsg->MaxCount = (ULONG_PTR)(ULONG)pS->cbBookmark1;
}

static void __RPC_USER IWineRowServer_GetRowsAtExprEval_0006(PMIDL_STUB_MESSAGE pStubMsg)
{
    struct _PARAM_STRUCT
    {
        IWineRowServer *This;
        HWATCHREGION hReserved1;
        HCHAPTER hReserved2;
        DBBKMARK cbBookmark;
        const BYTE *pBookmark;
        DBROWOFFSET lRowsOffset;
        DBROWCOUNT cRows;
        DBCOUNTITEM *pcRowsObtained;
        HROW **prghRows;
    } *pS = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pStubMsg->Offset = 0;
    pStubMsg->MaxCount = (ULONG_PTR)(ULONG)pS->cbBookmark;
}

static void __RPC_USER IWineRowServer_GetRowsByBookmarkExprEval_0007(PMIDL_STUB_MESSAGE pStubMsg)
{
    struct _PARAM_STRUCT
    {
        IWineRowServer *This;
        HCHAPTER hReserved;
        DBCOUNTITEM cRows;
        const DBBKMARK *rgcbBookmarks;
        const BYTE * *rgpBookmarks;
        HROW *rghRows;
        DBROWSTATUS *rgRowStatus;
    } *pS = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pStubMsg->Offset = 0;
    pStubMsg->MaxCount = (ULONG_PTR)(ULONG)pS->cRows;
}

static void __RPC_USER IWineRowServer_HashExprEval_0008(PMIDL_STUB_MESSAGE pStubMsg)
{
    struct _PARAM_STRUCT
    {
        IWineRowServer *This;
        HCHAPTER hReserved;
        DBBKMARK cBookmarks;
        const DBBKMARK *rgcbBookmarks;
        const BYTE * *rgpBookmarks;
        DBHASHVALUE *rgHashedValues;
        DBROWSTATUS *rgBookmarkStatus;
    } *pS = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pStubMsg->Offset = 0;
    pStubMsg->MaxCount = (ULONG_PTR)(ULONG)pS->cBookmarks;
}

static void __RPC_USER IWineRowServer_GetPropertiesExprEval_0009(PMIDL_STUB_MESSAGE pStubMsg)
{
    struct _PARAM_STRUCT
    {
        IWineRowServer *This;
        ULONG DECLSPEC_ALIGN(8) cPropertyIDSets;
        const DBPROPIDSET *rgPropertyIDSets;
        ULONG *pcPropertySets;
        DBPROPSET **prgPropertySets;
    } *pS = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pStubMsg->Offset = 0;
    pStubMsg->MaxCount = (ULONG_PTR)(ULONG)pS->cPropertyIDSets;
}

static void __RPC_USER row_server_DBBINDEXTExprEval_0010(PMIDL_STUB_MESSAGE pStubMsg)
{
    DBBINDEXT *pS = (DBBINDEXT *)(pStubMsg->StackTop - 0);
    pStubMsg->Offset = 0;
    pStubMsg->MaxCount = (ULONG_PTR)(ULONG)pS->ulExtension;
}

static void __RPC_USER IWineRowServer_CreateAccessorExprEval_0011(PMIDL_STUB_MESSAGE pStubMsg)
{
    struct _PARAM_STRUCT
    {
        IWineRowServer *This;
        DBACCESSORFLAGS DECLSPEC_ALIGN(8) dwAccessorFlags;
        DBCOUNTITEM cBindings;
        const DBBINDING *rgBindings;
        DBLENGTH cbRowSize;
        HACCESSOR *phAccessor;
        DBBINDSTATUS *rgStatus;
    } *pS = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pStubMsg->Offset = 0;
    pStubMsg->MaxCount = (ULONG_PTR)(ULONG)pS->cBindings;
}

static void __RPC_USER IWineRowServer_GetBindingsExprEval_0012(PMIDL_STUB_MESSAGE pStubMsg)
{
    struct _PARAM_STRUCT
    {
        IWineRowServer *This;
        HACCESSOR hAccessor;
        DBACCESSORFLAGS *pdwAccessorFlags;
        DBCOUNTITEM *pcBindings;
        DBBINDING **prgBindings;
    } *pS = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pStubMsg->Offset = 0;
    pStubMsg->MaxCount = (ULONG_PTR)(ULONG)*pS->pcBindings;
}

static const EXPR_EVAL ExprEvalRoutines[] =
{
    IWineRowServer_GetColumnsExprEval_0000,
    IWineRowServer_SetColumnsExprEval_0001,
    IWineRowServer_AddRefRowsExprEval_0002,
    IWineRowServer_GetNextRowsExprEval_0003,
    IWineRowServer_ReleaseRowsExprEval_0004,
    IWineRowServer_CompareExprEval_0005,
    IWineRowServer_GetRowsAtExprEval_0006,
    IWineRowServer_GetRowsByBookmarkExprEval_0007,
    IWineRowServer_HashExprEval_0008,
    IWineRowServer_GetPropertiesExprEval_0009,
    row_server_DBBINDEXTExprEval_0010,
    IWineRowServer_CreateAccessorExprEval_0011,
    IWineRowServer_GetBindingsExprEval_0012,
};

static const USER_MARSHAL_ROUTINE_QUADRUPLE UserMarshalRoutines[] =
{
    {
        (USER_MARSHAL_SIZING_ROUTINE)VARIANT_UserSize,
        (USER_MARSHAL_MARSHALLING_ROUTINE)VARIANT_UserMarshal,
        (USER_MARSHAL_UNMARSHALLING_ROUTINE)VARIANT_UserUnmarshal,
        (USER_MARSHAL_FREEING_ROUTINE)VARIANT_UserFree
    }
};

static const MIDL_STUB_DESC Object_StubDesc =
{
    0,
    NdrOleAllocate,
    NdrOleFree,
    {0}, 0, 0, ExprEvalRoutines, 0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    UserMarshalRoutines,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};

#if !defined(__RPC_WIN64__)
#error Invalid build platform for this proxy.
#endif

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure IWineRowServer::GetColumns) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 26 (parameter num_cols) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 32 (parameter in_data) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0xb6),	/* type offset = 182 */
/* 38 (parameter out_cols) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x52a),	/* type offset = 1322 */
/* 44 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 50 (procedure IWineRowServer::GetSourceRowset) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x14),	/* client buffer = 20 */
        NdrFcShort(0x18),	/* server buffer = 24 */
        0x45,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 76 (parameter riid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x260),	/* type offset = 608 */
/* 82 (parameter ppRowset) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x550),	/* type offset = 1360 */
/* 88 (parameter phRow) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0xb9,	/* FC_UINT3264 */
        0x0,
/* 94 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 100 (procedure IWineRowServer::Open) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x7),	/* method 7 */
        NdrFcShort(0x40),	/* stack size = 64 */
        NdrFcShort(0x30),	/* client buffer = 48 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x07,	/* 7 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 126 (parameter pUnkOuter) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x558),	/* type offset = 1368 */
/* 132 (parameter pColumnID) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x90),	/* type offset = 144 */
/* 138 (parameter rguidColumnType) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x8),	/* type offset = 8 */
/* 144 (parameter dwBindFlags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 150 (parameter riid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0x260),	/* type offset = 608 */
/* 156 (parameter ppUnk) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x30),	/* stack offset = 48 */
        NdrFcShort(0x57e),	/* type offset = 1406 */
/* 162 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x38),	/* stack offset = 56 */
        0x08,	/* FC_LONG */
        0x0,
/* 168 (procedure IWineRowServer::SetColumns) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x8),	/* method 8 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 194 (parameter num_cols) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 200 (parameter in_data) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x59c),	/* type offset = 1436 */
/* 206 (parameter status) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x5b6),	/* type offset = 1462 */
/* 212 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 218 (procedure IWineRowServer::AddRefRows) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x9),	/* method 9 */
        NdrFcShort(0x30),	/* stack size = 48 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x05,	/* 5 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 244 (parameter cRows) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 250 (parameter rghRows) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x5c6),	/* type offset = 1478 */
/* 256 (parameter rgRefCounts) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x5d8),	/* type offset = 1496 */
/* 262 (parameter rgRowStatus) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x5ea),	/* type offset = 1514 */
/* 268 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x28),	/* stack offset = 40 */
        0x08,	/* FC_LONG */
        0x0,
/* 274 (procedure IWineRowServer::GetData) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xa),	/* method 10 */
        NdrFcShort(0x30),	/* stack size = 48 */
        NdrFcShort(0x28),	/* client buffer = 40 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x05,	/* 5 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 300 (parameter hRow) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 306 (parameter hAccessor) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 312 (parameter pData) */
        NdrFcShort(0x11b),	/* flags: must size, must free, in, out, simple ref */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x5f6),	/* type offset = 1526 */
/* 318 (parameter size) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 324 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x28),	/* stack offset = 40 */
        0x08,	/* FC_LONG */
        0x0,
/* 330 (procedure IWineRowServer::GetNextRows) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xb),	/* method 11 */
        NdrFcShort(0x38),	/* stack size = 56 */
        NdrFcShort(0x30),	/* client buffer = 48 */
        NdrFcShort(0x18),	/* server buffer = 24 */
        0x45,
        0x06,	/* 6 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 356 (parameter hReserved) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 362 (parameter lRowsOffset) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 368 (parameter cRows) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 374 (parameter pcRowObtained) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0xb9,	/* FC_UINT3264 */
        0x0,
/* 380 (parameter prghRows) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0x620),	/* type offset = 1568 */
/* 386 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x30),	/* stack offset = 48 */
        0x08,	/* FC_LONG */
        0x0,
/* 392 (procedure IWineRowServer::ReleaseRows) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xc),	/* method 12 */
        NdrFcShort(0x38),	/* stack size = 56 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x06,	/* 6 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 418 (parameter cRows) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 424 (parameter rghRows) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x624),	/* type offset = 1572 */
/* 430 (parameter rgRowOptions) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x636),	/* type offset = 1590 */
/* 436 (parameter rgRefCounts) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x642),	/* type offset = 1602 */
/* 442 (parameter rgRowStatus) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0x654),	/* type offset = 1620 */
/* 448 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x30),	/* stack offset = 48 */
        0x08,	/* FC_LONG */
        0x0,
/* 454 (procedure IWineRowServer::RestartPosition) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xd),	/* method 13 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 480 (parameter hReserved) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 486 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 492 (procedure IWineRowServer::Compare) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xe),	/* method 14 */
        NdrFcShort(0x40),	/* stack size = 64 */
        NdrFcShort(0x30),	/* client buffer = 48 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x46,
        0x07,	/* 7 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 518 (parameter hReserved) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 524 (parameter cbBookmark1) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 530 (parameter pBookmark1) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x660),	/* type offset = 1632 */
/* 536 (parameter cbBookmark2) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 542 (parameter pBookmark2) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0x670),	/* type offset = 1648 */
/* 548 (parameter pComparison) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x30),	/* stack offset = 48 */
        0x09,	/* FC_ULONG */
        0x0,
/* 554 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x38),	/* stack offset = 56 */
        0x08,	/* FC_LONG */
        0x0,
/* 560 (procedure IWineRowServer::GetRowsAt) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xf),	/* method 15 */
        NdrFcShort(0x50),	/* stack size = 80 */
        NdrFcShort(0x50),	/* client buffer = 80 */
        NdrFcShort(0x18),	/* server buffer = 24 */
        0x47,
        0x09,	/* 9 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 586 (parameter hReserved1) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 592 (parameter hReserved2) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 598 (parameter cbBookmark) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 604 (parameter pBookmark) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x684),	/* type offset = 1668 */
/* 610 (parameter lRowsOffset) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x28),	/* stack offset = 40 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 616 (parameter cRows) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x30),	/* stack offset = 48 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 622 (parameter pcRowsObtained) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x38),	/* stack offset = 56 */
        0xb9,	/* FC_UINT3264 */
        0x0,
/* 628 (parameter prghRows) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x40),	/* stack offset = 64 */
        NdrFcShort(0x6ae),	/* type offset = 1710 */
/* 634 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x48),	/* stack offset = 72 */
        0x08,	/* FC_LONG */
        0x0,
/* 640 (procedure IWineRowServer::GetRowsByBookmark) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x10),	/* method 16 */
        NdrFcShort(0x40),	/* stack size = 64 */
        NdrFcShort(0x20),	/* client buffer = 32 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x07,	/* 7 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 666 (parameter hReserved) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 672 (parameter cRows) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 678 (parameter rgcbBookmarks) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x6b2),	/* type offset = 1714 */
/* 684 (parameter rgpBookmarks) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x6c4),	/* type offset = 1732 */
/* 690 (parameter rghRows) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0x6da),	/* type offset = 1754 */
/* 696 (parameter rgRowStatus) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x30),	/* stack offset = 48 */
        NdrFcShort(0x6ec),	/* type offset = 1772 */
/* 702 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x38),	/* stack offset = 56 */
        0x08,	/* FC_LONG */
        0x0,
/* 708 (procedure IWineRowServer::Hash) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x11),	/* method 17 */
        NdrFcShort(0x40),	/* stack size = 64 */
        NdrFcShort(0x20),	/* client buffer = 32 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x07,	/* 7 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 734 (parameter hReserved) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 740 (parameter cBookmarks) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 746 (parameter rgcbBookmarks) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x6f8),	/* type offset = 1784 */
/* 752 (parameter rgpBookmarks) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x70a),	/* type offset = 1802 */
/* 758 (parameter rgHashedValues) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0x720),	/* type offset = 1824 */
/* 764 (parameter rgBookmarkStatus) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x30),	/* stack offset = 48 */
        NdrFcShort(0x732),	/* type offset = 1842 */
/* 770 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x38),	/* stack offset = 56 */
        0x08,	/* FC_LONG */
        0x0,
/* 776 (procedure IWineRowServer::GetProperties) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x12),	/* method 18 */
        NdrFcShort(0x30),	/* stack size = 48 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x47,
        0x05,	/* 5 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 802 (parameter cPropertyIDSets) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 808 (parameter rgPropertyIDSets) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x774),	/* type offset = 1908 */
/* 814 (parameter pcPropertySets) */
        NdrFcShort(0x158),	/* flags: in, out, base type, simple ref */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x09,	/* FC_ULONG */
        0x0,
/* 820 (parameter prgPropertySets) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x7d6),	/* type offset = 2006 */
/* 826 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x28),	/* stack offset = 40 */
        0x08,	/* FC_LONG */
        0x0,
/* 832 (procedure IWineRowServer::GetReferencedRowset) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x13),	/* method 19 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x24),	/* client buffer = 36 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 858 (parameter iOrdinal) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 864 (parameter riid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x260),	/* type offset = 608 */
/* 870 (parameter ppReferencedRowset) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x7e6),	/* type offset = 2022 */
/* 876 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 882 (procedure IWineRowServer::GetSpecification) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x14),	/* method 20 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x14),	/* client buffer = 20 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 908 (parameter riid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x260),	/* type offset = 608 */
/* 914 (parameter ppSpecification) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x7f6),	/* type offset = 2038 */
/* 920 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 926 (procedure IWineRowServer::AddRefAccessor) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x15),	/* method 21 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x28),	/* client buffer = 40 */
        NdrFcShort(0x20),	/* server buffer = 32 */
        0x44,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 952 (parameter hAccessor) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 958 (parameter pcRefCount) */
        NdrFcShort(0x1a),	/* flags: must free, in, out */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x7fa),	/* type offset = 2042 */
/* 964 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 970 (procedure IWineRowServer::CreateAccessor) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x16),	/* method 22 */
        NdrFcShort(0x40),	/* stack size = 64 */
        NdrFcShort(0x28),	/* client buffer = 40 */
        NdrFcShort(0x18),	/* server buffer = 24 */
        0x47,
        0x07,	/* 7 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 996 (parameter dwAccessorFlags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 1002 (parameter cBindings) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 1008 (parameter rgBindings) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x870),	/* type offset = 2160 */
/* 1014 (parameter cbRowSize) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 1020 (parameter phAccessor) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x28),	/* stack offset = 40 */
        0xb9,	/* FC_UINT3264 */
        0x0,
/* 1026 (parameter rgStatus) */
        NdrFcShort(0x1b),	/* flags: must size, must free, in, out */
        NdrFcShort(0x30),	/* stack offset = 48 */
        NdrFcShort(0x884),	/* type offset = 2180 */
/* 1032 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x38),	/* stack offset = 56 */
        0x08,	/* FC_LONG */
        0x0,
/* 1038 (procedure IWineRowServer::GetBindings) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x17),	/* method 23 */
        NdrFcShort(0x30),	/* stack size = 48 */
        NdrFcShort(0x20),	/* client buffer = 32 */
        NdrFcShort(0x20),	/* server buffer = 32 */
        0x45,
        0x05,	/* 5 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1064 (parameter hAccessor) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 1070 (parameter pdwAccessorFlags) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x09,	/* FC_ULONG */
        0x0,
/* 1076 (parameter pcBindings) */
        NdrFcShort(0x158),	/* flags: in, out, base type, simple ref */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0xb9,	/* FC_UINT3264 */
        0x0,
/* 1082 (parameter prgBindings) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x8aa),	/* type offset = 2218 */
/* 1088 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x28),	/* stack offset = 40 */
        0x08,	/* FC_LONG */
        0x0,
/* 1094 (procedure IWineRowServer::ReleaseAccessor) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x18),	/* method 24 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x28),	/* client buffer = 40 */
        NdrFcShort(0x20),	/* server buffer = 32 */
        0x44,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1120 (parameter hAccessor) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0xb8,	/* FC_INT3264 */
        0x0,
/* 1126 (parameter pcRefCount) */
        NdrFcShort(0x1a),	/* flags: must free, in, out */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x8ae),	/* type offset = 2222 */
/* 1132 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 8 (GUID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (2) */
        0x5b,	/* FC_END */
/* 20 (GUID *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfff2),	/* Offset= -14 (8) */
/* 24 (union ) */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x7),	/* 7 */
        NdrFcLong(0x0),	/* 0 */
        NdrFcShort(0xffe8),	/* Offset= -24 (8) */
        NdrFcLong(0x1),	/* 1 */
        NdrFcShort(0xffe2),	/* Offset= -30 (8) */
        NdrFcLong(0x6),	/* 6 */
        NdrFcShort(0xffdc),	/* Offset= -36 (8) */
        NdrFcLong(0x2),	/* 2 */
        NdrFcShort(0xffd6),	/* Offset= -42 (8) */
        NdrFcLong(0x5),	/* 5 */
        NdrFcShort(0xffd0),	/* Offset= -48 (8) */
        NdrFcLong(0x3),	/* 3 */
        NdrFcShort(0xffd6),	/* Offset= -42 (20) */
        NdrFcLong(0x4),	/* 4 */
        NdrFcShort(0xffd0),	/* Offset= -48 (20) */
        NdrFcShort(0x0),
/* 72 (LPOLESTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 74 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 76 (union ) */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x7),	/* 7 */
        NdrFcLong(0x0),	/* 0 */
        NdrFcShort(0xfff4),	/* Offset= -12 (72) */
        NdrFcLong(0x2),	/* 2 */
        NdrFcShort(0xffee),	/* Offset= -18 (72) */
        NdrFcLong(0x3),	/* 3 */
        NdrFcShort(0xffe8),	/* Offset= -24 (72) */
        NdrFcLong(0x1),	/* 1 */
        NdrFcShort(0x8009),	/* Simple arm type: FC_ULONG */
        NdrFcLong(0x6),	/* 6 */
        NdrFcShort(0x8009),	/* Simple arm type: FC_ULONG */
        NdrFcLong(0x4),	/* 4 */
        NdrFcShort(0x8009),	/* Simple arm type: FC_ULONG */
        NdrFcLong(0x5),	/* 5 */
        NdrFcShort(0x8009),	/* Simple arm type: FC_ULONG */
        NdrFcShort(0x0),
/* 124 */
        0x2b,	/* FC_NON_ENCAPSULATED_UNION */
        0x9,	/* FC_ULONG */
        0x9,	/* Corr desc: field eKind, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x10),	/* offset = 16 */
        NdrFcShort(0x0),
        NdrFcShort(0xff94),	/* Offset= -108 (24) */
/* 134 */
        0x2b,	/* FC_NON_ENCAPSULATED_UNION */
        0x9,	/* FC_ULONG */
        0x9,	/* Corr desc: field eKind, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0xfff8),	/* offset = -8 */
        NdrFcShort(0x1),
        NdrFcShort(0xffbe),	/* Offset= -66 (76) */
/* 144 (DBID) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x20),	/* 32 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (150) */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe2),	/* Offset= -30 (124) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe6),	/* Offset= -26 (134) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 164 (wine_getcolumns_in) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x30),	/* 48 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (170) */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe2),	/* Offset= -30 (144) */
        0xb8,	/* FC_INT3264 */
        0x06,	/* FC_SHORT */
        0x01,	/* FC_BYTE */
        0x01,	/* FC_BYTE */
        0x40,	/* FC_STRUCTPAD4 */
        0x5b,	/* FC_END */
/* 182 (wine_getcolumns_in *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in GetColumns */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffdc),	/* Offset= -36 (164) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 204 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xffe8),	/* Offset= -24 (182) */
/* 208 (unsigned short[]) */
        0x1b,	/* FC_CARRAY */
        0x1,	/* 1 */
        NdrFcShort(0x2),	/* 2 */
        0x9,	/* Corr desc: field clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0xfffc),	/* offset = -4 */
        NdrFcShort(0x1),
        0x06,	/* FC_SHORT */
        0x5b,	/* FC_END */
/* 220 (FLAGGED_WORD_BLOB) */
        0x17,	/* FC_CSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0xfff0),	/* Offset= -16 (208) */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 230 (wireBSTR) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfff4),	/* Offset= -12 (220) */
/* 234 (CY) */
        0x15,	/* FC_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x8),	/* 8 */
        0x0b,	/* FC_HYPER */
        0x5b,	/* FC_END */
/* 240 (DECIMAL) */
        0x15,	/* FC_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x10),	/* 16 */
        0x06,	/* FC_SHORT */
        0x01,	/* FC_BYTE */
        0x01,	/* FC_BYTE */
        0x08,	/* FC_LONG */
        0x0b,	/* FC_HYPER */
        0x5b,	/* FC_END */
/* 250 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 268 (IDispatch *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00020400),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 286 (wireBSTR *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffac),	/* Offset= -84 (220) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 308 (SAFEARR_BSTR) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (320) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 320 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffdc),	/* Offset= -36 (286) */
/* 324 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 342 (IUnknown **) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffdc),	/* Offset= -36 (324) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 364 (SAFEARR_UNKNOWN) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (376) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 376 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffdc),	/* Offset= -36 (342) */
/* 380 (IDispatch *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00020400),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 398 (IDispatch **) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffdc),	/* Offset= -36 (380) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 420 (SAFEARR_DISPATCH) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (432) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 432 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffdc),	/* Offset= -36 (398) */
/* 436 (wireVARIANT *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0x332),	/* Offset= 818 (1272) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 458 (SAFEARR_VARIANT) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (470) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 470 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffdc),	/* Offset= -36 (436) */
/* 474 (IRecordInfo *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x0000002f),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 492 (byte *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x19,	/* Corr desc: field pointer clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x4),	/* offset = 4 */
        NdrFcShort(0x0),
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 504 (struct _wireBRECORD) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x18),	/* 24 */
        NdrFcShort(0x0),
        NdrFcShort(0xa),	/* Offset= 10 (520) */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffd6),	/* Offset= -42 (474) */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 520 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe2),	/* Offset= -30 (492) */
/* 524 (wireBRECORD *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffda),	/* Offset= -38 (504) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 546 (SAFEARR_BRECORD) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (558) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 558 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffdc),	/* Offset= -36 (524) */
/* 562 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 580 (IUnknown **) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffdc),	/* Offset= -36 (562) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 602 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 608 (IID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (602) */
        0x5b,	/* FC_END */
/* 620 (SAFEARR_HAVEIID) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x20),	/* 32 */
        NdrFcShort(0x0),
        NdrFcShort(0xa),	/* Offset= 10 (636) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe7),	/* Offset= -25 (608) */
        0x5b,	/* FC_END */
/* 636 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffc6),	/* Offset= -58 (580) */
/* 640 (byte *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x19,	/* Corr desc: field pointer clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 652 (BYTE_SIZEDARR) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (664) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 664 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe6),	/* Offset= -26 (640) */
/* 668 (unsigned short *) */
        0x1b,	/* FC_CARRAY */
        0x1,	/* 1 */
        NdrFcShort(0x2),	/* 2 */
        0x19,	/* Corr desc: field pointer clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        0x06,	/* FC_SHORT */
        0x5b,	/* FC_END */
/* 680 (WORD_SIZEDARR) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (692) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 692 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe6),	/* Offset= -26 (668) */
/* 696 (ULONG *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x19,	/* Corr desc: field pointer clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 708 (DWORD_SIZEDARR) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (720) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 720 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe6),	/* Offset= -26 (696) */
/* 724 (hyper *) */
        0x1b,	/* FC_CARRAY */
        0x7,	/* 7 */
        NdrFcShort(0x8),	/* 8 */
        0x19,	/* Corr desc: field pointer clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        0x0b,	/* FC_HYPER */
        0x5b,	/* FC_END */
/* 736 (HYPER_SIZEDARR) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (748) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 748 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe6),	/* Offset= -26 (724) */
/* 752 (SAFEARRAYUNION) */
        0x2a,	/* FC_ENCAPSULATED_UNION */
        0x89,	/* Switch type= FC_ULONG */
        NdrFcShort(0x20),	/* 32 */
        NdrFcShort(0xa),	/* 10 */
        NdrFcLong(0x8),	/* 8 */
        NdrFcShort(0xfe3a),	/* Offset= -454 (308) */
        NdrFcLong(0xd),	/* 13 */
        NdrFcShort(0xfe6c),	/* Offset= -404 (364) */
        NdrFcLong(0x9),	/* 9 */
        NdrFcShort(0xfe9e),	/* Offset= -354 (420) */
        NdrFcLong(0xc),	/* 12 */
        NdrFcShort(0xfebe),	/* Offset= -322 (458) */
        NdrFcLong(0x24),	/* 36 */
        NdrFcShort(0xff10),	/* Offset= -240 (546) */
        NdrFcLong(0x800d),	/* 32781 */
        NdrFcShort(0xff54),	/* Offset= -172 (620) */
        NdrFcLong(0x10),	/* 16 */
        NdrFcShort(0xff6e),	/* Offset= -146 (652) */
        NdrFcLong(0x2),	/* 2 */
        NdrFcShort(0xff84),	/* Offset= -124 (680) */
        NdrFcLong(0x3),	/* 3 */
        NdrFcShort(0xff9a),	/* Offset= -102 (708) */
        NdrFcLong(0x14),	/* 20 */
        NdrFcShort(0xffb0),	/* Offset= -80 (736) */
        NdrFcShort(0xffff),
/* 820 (SAFEARRAYBOUND) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 828 (SAFEARRAYBOUND[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x7,	/* Corr desc: field cDims, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0xffc8),	/* offset = -56 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffec),	/* Offset= -20 (820) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 844 (struct _wireSAFEARRAY) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x38),	/* 56 */
        NdrFcShort(0xffec),	/* Offset= -20 (828) */
        NdrFcShort(0x0),	/* Offset= 0 (850) */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xff95),	/* Offset= -107 (752) */
        0x5b,	/* FC_END */
/* 862 (wireSAFEARRAY) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffec),	/* Offset= -20 (844) */
/* 866 (signed char *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x02,	/* FC_CHAR */
        0x5c,	/* FC_PAD */
/* 870 (USHORT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x07,	/* FC_USHORT */
        0x5c,	/* FC_PAD */
/* 874 (ULONG *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 878 (INT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 882 (UINT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 886 (BYTE *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x01,	/* FC_BYTE */
        0x5c,	/* FC_PAD */
/* 890 (SHORT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x06,	/* FC_SHORT */
        0x5c,	/* FC_PAD */
/* 894 (LONG *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 898 (FLOAT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x0a,	/* FC_FLOAT */
        0x5c,	/* FC_PAD */
/* 902 (DOUBLE *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x0c,	/* FC_DOUBLE */
        0x5c,	/* FC_PAD */
/* 906 (VARIANT_BOOL *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x06,	/* FC_SHORT */
        0x5c,	/* FC_PAD */
/* 910 (SCODE *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 914 (DATE *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x0c,	/* FC_DOUBLE */
        0x5c,	/* FC_PAD */
/* 918 (wireBSTR) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfd44),	/* Offset= -700 (220) */
/* 922 (wireBSTR *) */
        0x12, 0x10,		/* FC_UP [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (918) */
/* 926 (wireVARIANT) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0x158),	/* Offset= 344 (1272) */
/* 930 (wireVARIANT *) */
        0x12, 0x10,		/* FC_UP [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (926) */
/* 934 (CY *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfd42),	/* Offset= -702 (234) */
/* 938 (DECIMAL *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfd44),	/* Offset= -700 (240) */
/* 942 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 960 (IUnknown **) */
        0x12, 0x10,		/* FC_UP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (942) */
/* 964 (IDispatch *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00020400),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 982 (IDispatch **) */
        0x12, 0x10,		/* FC_UP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (964) */
/* 986 (wireSAFEARRAY) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xff70),	/* Offset= -144 (844) */
/* 990 (wireSAFEARRAY *) */
        0x12, 0x10,		/* FC_UP [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (986) */
/* 994 (wireBRECORD) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfe14),	/* Offset= -492 (504) */
/* 998 (union ) */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x2b),	/* 43 */
        NdrFcLong(0x0),	/* 0 */
        NdrFcShort(0x0),	/* No type */
        NdrFcLong(0x1),	/* 1 */
        NdrFcShort(0x0),	/* No type */
        NdrFcLong(0x10),	/* 16 */
        NdrFcShort(0x8002),	/* Simple arm type: FC_CHAR */
        NdrFcLong(0x12),	/* 18 */
        NdrFcShort(0x8007),	/* Simple arm type: FC_USHORT */
        NdrFcLong(0x13),	/* 19 */
        NdrFcShort(0x8009),	/* Simple arm type: FC_ULONG */
        NdrFcLong(0x16),	/* 22 */
        NdrFcShort(0x8008),	/* Simple arm type: FC_LONG */
        NdrFcLong(0x17),	/* 23 */
        NdrFcShort(0x8009),	/* Simple arm type: FC_ULONG */
        NdrFcLong(0x11),	/* 17 */
        NdrFcShort(0x8001),	/* Simple arm type: FC_BYTE */
        NdrFcLong(0x2),	/* 2 */
        NdrFcShort(0x8006),	/* Simple arm type: FC_SHORT */
        NdrFcLong(0x3),	/* 3 */
        NdrFcShort(0x8008),	/* Simple arm type: FC_LONG */
        NdrFcLong(0x4),	/* 4 */
        NdrFcShort(0x800a),	/* Simple arm type: FC_FLOAT */
        NdrFcLong(0x5),	/* 5 */
        NdrFcShort(0x800c),	/* Simple arm type: FC_DOUBLE */
        NdrFcLong(0xb),	/* 11 */
        NdrFcShort(0x8006),	/* Simple arm type: FC_SHORT */
        NdrFcLong(0xa),	/* 10 */
        NdrFcShort(0x8008),	/* Simple arm type: FC_LONG */
        NdrFcLong(0x7),	/* 7 */
        NdrFcShort(0x800c),	/* Simple arm type: FC_DOUBLE */
        NdrFcLong(0x8),	/* 8 */
        NdrFcShort(0xff4e),	/* Offset= -178 (918) */
        NdrFcLong(0x6),	/* 6 */
        NdrFcShort(0xfc9c),	/* Offset= -868 (234) */
        NdrFcLong(0xe),	/* 14 */
        NdrFcShort(0xfc9c),	/* Offset= -868 (240) */
        NdrFcLong(0xd),	/* 13 */
        NdrFcShort(0xfca0),	/* Offset= -864 (250) */
        NdrFcLong(0x9),	/* 9 */
        NdrFcShort(0xfcac),	/* Offset= -852 (268) */
        NdrFcLong(0x2000),	/* 8192 */
        NdrFcShort(0xff74),	/* Offset= -140 (986) */
        NdrFcLong(0x4010),	/* 16400 */
        NdrFcShort(0xfef6),	/* Offset= -266 (866) */
        NdrFcLong(0x4012),	/* 16402 */
        NdrFcShort(0xfef4),	/* Offset= -268 (870) */
        NdrFcLong(0x4013),	/* 16403 */
        NdrFcShort(0xfef2),	/* Offset= -270 (874) */
        NdrFcLong(0x4016),	/* 16406 */
        NdrFcShort(0xfef0),	/* Offset= -272 (878) */
        NdrFcLong(0x4017),	/* 16407 */
        NdrFcShort(0xfeee),	/* Offset= -274 (882) */
        NdrFcLong(0x4011),	/* 16401 */
        NdrFcShort(0xfeec),	/* Offset= -276 (886) */
        NdrFcLong(0x4002),	/* 16386 */
        NdrFcShort(0xfeea),	/* Offset= -278 (890) */
        NdrFcLong(0x4003),	/* 16387 */
        NdrFcShort(0xfee8),	/* Offset= -280 (894) */
        NdrFcLong(0x4004),	/* 16388 */
        NdrFcShort(0xfee6),	/* Offset= -282 (898) */
        NdrFcLong(0x4005),	/* 16389 */
        NdrFcShort(0xfee4),	/* Offset= -284 (902) */
        NdrFcLong(0x400b),	/* 16395 */
        NdrFcShort(0xfee2),	/* Offset= -286 (906) */
        NdrFcLong(0x400a),	/* 16394 */
        NdrFcShort(0xfee0),	/* Offset= -288 (910) */
        NdrFcLong(0x4007),	/* 16391 */
        NdrFcShort(0xfede),	/* Offset= -290 (914) */
        NdrFcLong(0x4008),	/* 16392 */
        NdrFcShort(0xfee0),	/* Offset= -288 (922) */
        NdrFcLong(0x400c),	/* 16396 */
        NdrFcShort(0xfee2),	/* Offset= -286 (930) */
        NdrFcLong(0x4006),	/* 16390 */
        NdrFcShort(0xfee0),	/* Offset= -288 (934) */
        NdrFcLong(0x400e),	/* 16398 */
        NdrFcShort(0xfede),	/* Offset= -290 (938) */
        NdrFcLong(0x400d),	/* 16397 */
        NdrFcShort(0xfeee),	/* Offset= -274 (960) */
        NdrFcLong(0x4009),	/* 16393 */
        NdrFcShort(0xfefe),	/* Offset= -258 (982) */
        NdrFcLong(0x6000),	/* 24576 */
        NdrFcShort(0xff00),	/* Offset= -256 (990) */
        NdrFcLong(0x24),	/* 36 */
        NdrFcShort(0xfefe),	/* Offset= -258 (994) */
        NdrFcLong(0x4024),	/* 16420 */
        NdrFcShort(0xfef8),	/* Offset= -264 (994) */
        NdrFcShort(0xffff),
/* 1262 */
        0x2b,	/* FC_NON_ENCAPSULATED_UNION */
        0x7,	/* FC_USHORT */
        0x7,	/* Corr desc: field vt, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0xfff8),	/* offset = -8 */
        NdrFcShort(0x1),
        NdrFcShort(0xfef0),	/* Offset= -272 (998) */
/* 1272 (struct _wireVARIANT) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x20),	/* 32 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (1278) */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe6),	/* Offset= -26 (1262) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1292 (wireVARIANT) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffea),	/* Offset= -22 (1272) */
/* 1296 (VARIANT) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x0),	/* Function offset= 0 */
        NdrFcShort(0x18),	/* 24 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xfff4),	/* Offset= -12 (1292) */
/* 1306 (wine_getcolumns_out) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x28),	/* 40 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (1312) */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffec),	/* Offset= -20 (1296) */
        0xb8,	/* FC_INT3264 */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x5b,	/* FC_END */
/* 1322 (wine_getcolumns_out *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x7,	/* 7 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in GetColumns */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffde),	/* Offset= -34 (1306) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1344 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xffe8),	/* Offset= -24 (1322) */
/* 1348 (REFIID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfd1a),	/* Offset= -742 (608) */
/* 1352 (IUnknown *) */
        0x2f,  /* FC_IP */
        0x5c,  /* FC_PAD */
        0x2b,	/* Corr desc: parameter riid, FC_HYPER */
        0x0,	/* no operators */
        NdrFcShort(0x8),	/* offset = 8 */
        NdrFcShort(0x5),
/* 1360 (IUnknown **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xfff6),	/* Offset= -10 (1352) */
/* 1364 (HROW *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0xb9,	/* FC_UINT3264 */
        0x5c,	/* FC_PAD */
/* 1368 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 1386 (DBID *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfb24),	/* Offset= -1244 (144) */
/* 1390 (REFGUID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfa98),	/* Offset= -1384 (8) */
/* 1394 (REFIID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfcec),	/* Offset= -788 (608) */
/* 1398 (IUnknown *) */
        0x2f,  /* FC_IP */
        0x5c,  /* FC_PAD */
        0x2b,	/* Corr desc: parameter riid, FC_HYPER */
        0x0,	/* no operators */
        NdrFcShort(0x28),	/* offset = 40 */
        NdrFcShort(0x5),
/* 1406 (IUnknown **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xfff6),	/* Offset= -10 (1398) */
/* 1410 (wine_setcolumns_in) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x58),	/* 88 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (1416) */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xff84),	/* Offset= -124 (1296) */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfb00),	/* Offset= -1280 (144) */
        0xb8,	/* FC_INT3264 */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0xb8,	/* FC_INT3264 */
        0x06,	/* FC_SHORT */
        0x01,	/* FC_BYTE */
        0x01,	/* FC_BYTE */
        0x40,	/* FC_STRUCTPAD4 */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1436 (wine_setcolumns_in *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x7,	/* 7 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in SetColumns */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x1),	/* 1 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffd4),	/* Offset= -44 (1410) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1458 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xffe8),	/* Offset= -24 (1436) */
/* 1462 (DBSTATUS *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x20,	/* Corr desc: parameter in SetColumns */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x1),	/* 1 */
        NdrFcShort(0x0),
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 1474 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff2),	/* Offset= -14 (1462) */
/* 1478 (const HROW[]) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in AddRefRows */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x2),	/* 2 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0xb8,	/* FC_INT3264 */
        0x5b,	/* FC_END */
/* 1496 (DBREFCOUNT[]) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in AddRefRows */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x2),	/* 2 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0xb8,	/* FC_INT3264 */
        0x5b,	/* FC_END */
/* 1514 (DBROWSTATUS[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x20,	/* Corr desc: parameter in AddRefRows */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x2),	/* 2 */
        NdrFcShort(0x0),
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 1526 (BYTE *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x29,	/* Corr desc: parameter size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x20),	/* offset = 32 */
        NdrFcShort(0x0),
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 1538 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff2),	/* Offset= -14 (1526) */
/* 1542 (DBCOUNTITEM *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0xb9,	/* FC_UINT3264 */
        0x5c,	/* FC_PAD */
/* 1546 (HROW *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in GetNextRows */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x3),	/* 3 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0xb8,	/* FC_INT3264 */
        0x5b,	/* FC_END */
/* 1564 */
        0x13, 0x0,	/* FC_OP */
        NdrFcShort(0xffec),	/* Offset= -20 (1546) */
/* 1568 (HROW **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (1564) */
/* 1572 (const HROW[]) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in ReleaseRows */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x4),	/* 4 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0xb8,	/* FC_INT3264 */
        0x5b,	/* FC_END */
/* 1590 (DBROWOPTIONS[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x20,	/* Corr desc: parameter in ReleaseRows */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x4),	/* 4 */
        NdrFcShort(0x0),
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 1602 (DBREFCOUNT[]) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in ReleaseRows */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x4),	/* 4 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0xb8,	/* FC_INT3264 */
        0x5b,	/* FC_END */
/* 1620 (DBROWSTATUS[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x20,	/* Corr desc: parameter in ReleaseRows */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x4),	/* 4 */
        NdrFcShort(0x0),
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 1632 (const BYTE *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x20,	/* Corr desc: parameter in Compare */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x5),	/* 5 */
        NdrFcShort(0x0),
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 1644 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff2),	/* Offset= -14 (1632) */
/* 1648 (const BYTE *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x20,	/* Corr desc: parameter in Compare */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x5),	/* 5 */
        NdrFcShort(0x0),
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 1660 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff2),	/* Offset= -14 (1648) */
/* 1664 (DBCOMPARE *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 1668 (const BYTE *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x20,	/* Corr desc: parameter in GetRowsAt */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x6),	/* 6 */
        NdrFcShort(0x0),
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 1680 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff2),	/* Offset= -14 (1668) */
/* 1684 (DBCOUNTITEM *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0xb9,	/* FC_UINT3264 */
        0x5c,	/* FC_PAD */
/* 1688 (HROW *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in GetRowsAt */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x6),	/* 6 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0xb8,	/* FC_INT3264 */
        0x5b,	/* FC_END */
/* 1706 */
        0x13, 0x0,	/* FC_OP */
        NdrFcShort(0xffec),	/* Offset= -20 (1688) */
/* 1710 (HROW **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (1706) */
/* 1714 (const DBBKMARK[]) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in GetRowsByBookmark */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x7),	/* 7 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0xb8,	/* FC_INT3264 */
        0x5b,	/* FC_END */
/* 1732 (const BYTE *[]) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in GetRowsByBookmark */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x7),	/* 7 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x01,	/* FC_BYTE */
        0x5c,	/* FC_PAD */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1754 (HROW[]) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in GetRowsByBookmark */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x7),	/* 7 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0xb8,	/* FC_INT3264 */
        0x5b,	/* FC_END */
/* 1772 (DBROWSTATUS[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x20,	/* Corr desc: parameter in GetRowsByBookmark */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x7),	/* 7 */
        NdrFcShort(0x0),
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 1784 (const DBBKMARK[]) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in Hash */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0xb8,	/* FC_INT3264 */
        0x5b,	/* FC_END */
/* 1802 (const BYTE *[]) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in Hash */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x01,	/* FC_BYTE */
        0x5c,	/* FC_PAD */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1824 (DBHASHVALUE[]) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in Hash */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0xb8,	/* FC_INT3264 */
        0x5b,	/* FC_END */
/* 1842 (DBROWSTATUS[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x20,	/* Corr desc: parameter in Hash */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 1854 (DBPROPID *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x19,	/* Corr desc: field pointer cPropertyIDs, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x8),	/* offset = 8 */
        NdrFcShort(0x0),
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 1866 (DBPROPIDSET) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x20),	/* 32 */
        NdrFcShort(0x0),
        NdrFcShort(0xa),	/* Offset= 10 (1882) */
        0x36,	/* FC_POINTER */
        0x08,	/* FC_LONG */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xf8b2),	/* Offset= -1870 (8) */
        0x40,	/* FC_STRUCTPAD4 */
        0x5b,	/* FC_END */
/* 1882 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe2),	/* Offset= -30 (1854) */
/* 1886 (const DBPROPIDSET *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in GetProperties */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x9),	/* 9 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffda),	/* Offset= -38 (1866) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1908 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xffe8),	/* Offset= -24 (1886) */
/* 1912 (ULONG *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 1916 (DBPROP) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x48),	/* 72 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (1922) */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xf906),	/* Offset= -1786 (144) */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfd82),	/* Offset= -638 (1296) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1938 (DBPROP *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x7,	/* 7 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer cProperties, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x8),	/* offset = 8 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffd8),	/* Offset= -40 (1916) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1960 (DBPROPSET) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x20),	/* 32 */
        NdrFcShort(0x0),
        NdrFcShort(0xa),	/* Offset= 10 (1976) */
        0x36,	/* FC_POINTER */
        0x08,	/* FC_LONG */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xf854),	/* Offset= -1964 (8) */
        0x40,	/* FC_STRUCTPAD4 */
        0x5b,	/* FC_END */
/* 1976 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffd8),	/* Offset= -40 (1938) */
/* 1980 (DBPROPSET *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x29,	/* Corr desc: parameter pcPropertySets, FC_ULONG */
        0x54,	/* FC_DEREFERENCE */
        NdrFcShort(0x18),	/* offset = 24 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffda),	/* Offset= -38 (1960) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 2002 */
        0x13, 0x0,	/* FC_OP */
        NdrFcShort(0xffe8),	/* Offset= -24 (1980) */
/* 2006 (DBPROPSET **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (2002) */
/* 2010 (REFIID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfa84),	/* Offset= -1404 (608) */
/* 2014 (IUnknown *) */
        0x2f,  /* FC_IP */
        0x5c,  /* FC_PAD */
        0x2b,	/* Corr desc: parameter riid, FC_HYPER */
        0x0,	/* no operators */
        NdrFcShort(0x10),	/* offset = 16 */
        NdrFcShort(0x5),
/* 2022 (IUnknown **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xfff6),	/* Offset= -10 (2014) */
/* 2026 (REFIID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfa74),	/* Offset= -1420 (608) */
/* 2030 (IUnknown *) */
        0x2f,  /* FC_IP */
        0x5c,  /* FC_PAD */
        0x2b,	/* Corr desc: parameter riid, FC_HYPER */
        0x0,	/* no operators */
        NdrFcShort(0x8),	/* offset = 8 */
        NdrFcShort(0x5),
/* 2038 (IUnknown **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xfff6),	/* Offset= -10 (2030) */
/* 2042 (DBREFCOUNT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0xb9,	/* FC_UINT3264 */
        0x5c,	/* FC_PAD */
/* 2046 (ITypeInfo *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00020401),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 2064 (DBOBJECT) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x14),	/* 20 */
        0x08,	/* FC_LONG */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfa49),	/* Offset= -1463 (608) */
        0x5b,	/* FC_END */
/* 2074 (BYTE *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x10,	/* Corr desc: field pointer in DBBINDEXT */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0xa),	/* 10 */
        NdrFcShort(0x0),
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 2086 (DBBINDEXT) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (2098) */
        0x36,	/* FC_POINTER */
        0xb8,	/* FC_INT3264 */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 2098 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe6),	/* Offset= -26 (2074) */
/* 2102 (DBBINDING) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x58),	/* 88 */
        NdrFcShort(0x0),
        NdrFcShort(0x16),	/* Offset= 22 (2130) */
        0xb8,	/* FC_INT3264 */
        0xb8,	/* FC_INT3264 */
        0xb8,	/* FC_INT3264 */
        0xb8,	/* FC_INT3264 */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffba),	/* Offset= -70 (2046) */
        0x36,	/* FC_POINTER */
        0x36,	/* FC_POINTER */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0xb8,	/* FC_INT3264 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x01,	/* FC_BYTE */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 2130 (DBOBJECT *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffbc),	/* Offset= -68 (2064) */
/* 2134 (DBBINDEXT *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffce),	/* Offset= -50 (2086) */
/* 2138 (const DBBINDING *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in CreateAccessor */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0xb),	/* 11 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffca),	/* Offset= -54 (2102) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 2160 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xffe8),	/* Offset= -24 (2138) */
/* 2164 (HACCESSOR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0xb9,	/* FC_UINT3264 */
        0x5c,	/* FC_PAD */
/* 2168 (DBBINDSTATUS *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x20,	/* Corr desc: parameter in CreateAccessor */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0xb),	/* 11 */
        NdrFcShort(0x0),
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 2180 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xfff2),	/* Offset= -14 (2168) */
/* 2184 (DBACCESSORFLAGS *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 2188 (DBCOUNTITEM *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0xb9,	/* FC_UINT3264 */
        0x5c,	/* FC_PAD */
/* 2192 (DBBINDING *) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x20,	/* Corr desc: parameter in GetBindings */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0xc),	/* 12 */
        NdrFcShort(0x0),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xff94),	/* Offset= -108 (2102) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 2214 */
        0x13, 0x0,	/* FC_OP */
        NdrFcShort(0xffe8),	/* Offset= -24 (2192) */
/* 2218 (DBBINDING **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (2214) */
/* 2222 (DBREFCOUNT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0xb9,	/* FC_UINT3264 */
        0x5c,	/* FC_PAD */
        0x0
    }
};

static const CInterfaceProxyVtbl* const _row_server_ProxyVtblList[] =
{
    (const CInterfaceProxyVtbl*)&_IWineRowServerProxyVtbl,
    0
};

static const CInterfaceStubVtbl* const _row_server_StubVtblList[] =
{
    &_IWineRowServerStubVtbl,
    0
};

static PCInterfaceName const _row_server_InterfaceNamesList[] =
{
    "IWineRowServer",
    0
};

static int __stdcall _row_server_IID_Lookup(const IID* pIID, int* pIndex)
{
    int low = 0, high = 0;

    while (low <= high)
    {
        int pos = (low + high) / 2;
        int res = IID_GENERIC_CHECK_IID(_row_server, pIID, pos);
        if (!res) { *pIndex = pos; return 1; }
        if (res > 0) low = pos + 1;
        else high = pos - 1;
    }
    return 0;
}

const ExtendedProxyFileInfo row_server_ProxyFileInfo =
{
    (const PCInterfaceProxyVtblList*)_row_server_ProxyVtblList,
    (const PCInterfaceStubVtblList*)_row_server_StubVtblList,
    _row_server_InterfaceNamesList,
    0,
    _row_server_IID_Lookup,
    1,
    2,
    0,
    0,
    0,
    0
};
