/*** Autogenerated by WIDL 9.21 from dlls/ntoskrnl.exe/plugplay.idl - Do not edit ***/
#include <string.h>

#include "plugplay.h"

#define TYPE_FORMAT_STRING_SIZE 67
#define PROC_FORMAT_STRING_SIZE 183

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

/*****************************************************************************
 * plugplay interface
 */

handle_t plugplay_binding_handle;

static const unsigned char * const plugplay__RpcProtseqEndpoint[][2] =
{
    { (const unsigned char *)"ncacn_np", (const unsigned char *)"\\pipe\\wine_plugplay" },
};

static const RPC_CLIENT_INTERFACE plugplay___RpcClientInterface =
{
    sizeof(RPC_CLIENT_INTERFACE),
    {{0x57c680ac,0x7bce,0x4f39,{0x97,0xfd,0xff,0xea,0x56,0x67,0x54,0xd5}},{0,0}},
    {{0x8a885d04,0x1ceb,0x11c9,{0x9f,0xe8,0x08,0x00,0x2b,0x10,0x48,0x60}},{2,0}},
    0,
    1,
    (PRPC_PROTSEQ_ENDPOINT)plugplay__RpcProtseqEndpoint,
    0,
    0,
    0,
};
RPC_IF_HANDLE plugplay_v0_0_c_ifspec = (RPC_IF_HANDLE)& plugplay___RpcClientInterface;

static const MIDL_STUB_DESC plugplay_StubDesc;

plugplay_rpc_handle __cdecl plugplay_register_listener(
    void)
{
    CLIENT_CALL_RETURN _RetVal;

    _RetVal = NdrClientCall2( &plugplay_StubDesc,
                              &__MIDL_ProcFormatString.Format[0] );
    return (plugplay_rpc_handle)_RetVal.Simple;
}

DWORD __cdecl plugplay_get_event(
    plugplay_rpc_handle handle,
    WCHAR **path,
    BYTE **data,
    unsigned int *size)
{
    CLIENT_CALL_RETURN _RetVal;

    _RetVal = NdrClientCall2( &plugplay_StubDesc,
                              &__MIDL_ProcFormatString.Format[32],
                              handle,
                              path,
                              data,
                              size );
    return (DWORD)_RetVal.Simple;
}

void __cdecl plugplay_unregister_listener(
    plugplay_rpc_handle handle)
{
    NdrClientCall2( &plugplay_StubDesc,
                    &__MIDL_ProcFormatString.Format[94],
                    handle );
}

void __cdecl plugplay_send_event(
    const WCHAR *path,
    DWORD event_code,
    const BYTE *data,
    unsigned int size)
{
    NdrClientCall2( &plugplay_StubDesc,
                    &__MIDL_ProcFormatString.Format[132],
                    path,
                    event_code,
                    data,
                    size );
}

#if !defined(__RPC_WIN64__)
#error  Invalid build platform for this stub.
#endif

static const MIDL_STUB_DESC plugplay_StubDesc =
{
    (void *)& plugplay___RpcClientInterface,
    MIDL_user_allocate,
    MIDL_user_free,
    {
        &plugplay_binding_handle,
    },
    0,
    0,
    0,
    0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};


static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure plugplay::plugplay_register_listener) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x0),	/* method 0 */
        NdrFcShort(0x8),	/* stack size = 8 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x18),	/* server buffer = 24 */
        0x44,
        0x01,	/* 1 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 26 (return value) */
        NdrFcShort(0x30),	/* flags: out, return */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x2),	/* type offset = 2 */
/* 32 (procedure plugplay::plugplay_get_event) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x1),	/* method 1 */
        NdrFcShort(0x28),	/* stack size = 40 */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x45,
        0x05,	/* 5 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 64 (parameter handle) */
        NdrFcShort(0x8),	/* flags: in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x6),	/* type offset = 6 */
/* 70 (parameter path) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xe),	/* type offset = 14 */
/* 76 (parameter data) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x22),	/* type offset = 34 */
/* 82 (parameter size) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x09,	/* FC_ULONG */
        0x0,
/* 88 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 94 (procedure plugplay::plugplay_unregister_listener) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x2),	/* method 2 */
        NdrFcShort(0x8),	/* stack size = 8 */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x00,
        0x00,	/* param 0 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x0),	/* server buffer = 0 */
        0x40,
        0x01,	/* 1 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 126 (parameter handle) */
        NdrFcShort(0x8),	/* flags: in */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x2a),	/* type offset = 42 */
/* 132 (procedure plugplay::plugplay_send_event) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x0),	/* server buffer = 0 */
        0x42,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 158 (parameter path) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x30),	/* type offset = 48 */
/* 164 (parameter event_code) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 170 (parameter data) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x32),	/* type offset = 50 */
/* 176 (parameter size) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (plugplay_rpc_handle) */
        0x30,	/* FC_BIND_CONTEXT */
        0x30,	/* Context flags: return, out, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 6 (plugplay_rpc_handle) */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,	/* Context flags: can't be null, in, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 10 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 12 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 14 (WCHAR **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (10) */
/* 18 (BYTE *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x29,	/* Corr desc: parameter size, FC_ULONG */
        0x54,	/* FC_DEREFERENCE */
        NdrFcShort(0x18),	/* offset = 24 */
        NdrFcShort(0x0),
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 30 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xfff2),	/* Offset= -14 (18) */
/* 34 (BYTE **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (30) */
/* 38 (unsigned int *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 42 (plugplay_rpc_handle) */
        0x30,	/* FC_BIND_CONTEXT */
        0x41,	/* Context flags: can't be null, in, */
        0x0,	/* rundown routine */
        0, /* FIXME: param num */
/* 46 (const WCHAR *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 48 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 50 (const BYTE *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x29,	/* Corr desc: parameter size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x18),	/* offset = 24 */
        NdrFcShort(0x0),
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 62 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xfff2),	/* Offset= -14 (50) */
        0x0
    }
};

