/*** Autogenerated by WIDL 9.21 from dlls/msi/winemsi.idl - Do not edit ***/
#include <string.h>

#include "winemsi.h"

#define TYPE_FORMAT_STRING_SIZE 419
#define PROC_FORMAT_STRING_SIZE 1745

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

/*****************************************************************************
 * IWineMsiRemote interface
 */

static RPC_DISPATCH_TABLE IWineMsiRemote_v0_0_DispatchTable;
static const MIDL_SERVER_INFO IWineMsiRemote_ServerInfo;

static const RPC_SERVER_INTERFACE IWineMsiRemote___RpcServerInterface =
{
    sizeof(RPC_SERVER_INTERFACE),
    {{0x56d58b64,0x8780,0x4c22,{0xa8,0xbc,0x8b,0x0b,0x29,0xe4,0xa9,0xf8}},{0,0}},
    {{0x8a885d04,0x1ceb,0x11c9,{0x9f,0xe8,0x08,0x00,0x2b,0x10,0x48,0x60}},{2,0}},
    &IWineMsiRemote_v0_0_DispatchTable,
    0,
    0,
    0,
    &IWineMsiRemote_ServerInfo,
    0,
};
RPC_IF_HANDLE s_IWineMsiRemote_v0_0_s_ifspec = (RPC_IF_HANDLE)& IWineMsiRemote___RpcServerInterface;

static const MIDL_STUB_DESC IWineMsiRemote_StubDesc;

#if !defined(__RPC_WIN64__)
#error  Invalid build platform for this stub.
#endif

static const unsigned short IWineMsiRemote_FormatStringOffsetTable[] =
{
    0,  /* remote_ViewClose */
    38,  /* remote_ViewExecute */
    82,  /* remote_ViewFetch */
    126,  /* remote_ViewGetColumnInfo */
    176,  /* remote_ViewGetError */
    220,  /* remote_ViewModify */
    276,  /* remote_DatabaseIsTablePersistent */
    320,  /* remote_DatabaseGetPrimaryKeys */
    370,  /* remote_DatabaseGetSummaryInformation */
    420,  /* remote_DatabaseOpenView */
    470,  /* remote_SummaryInfoGetPropertyCount */
    514,  /* remote_SummaryInfoGetProperty */
    582,  /* remote_GetActiveDatabase */
    620,  /* remote_GetProperty */
    676,  /* remote_SetProperty */
    726,  /* remote_ProcessMessage */
    776,  /* remote_DoAction */
    820,  /* remote_Sequence */
    870,  /* remote_GetTargetPath */
    920,  /* remote_SetTargetPath */
    970,  /* remote_GetSourcePath */
    1020,  /* remote_GetMode */
    1064,  /* remote_SetMode */
    1114,  /* remote_GetFeatureState */
    1170,  /* remote_SetFeatureState */
    1220,  /* remote_GetComponentState */
    1276,  /* remote_SetComponentState */
    1326,  /* remote_GetLanguage */
    1364,  /* remote_SetInstallLevel */
    1408,  /* remote_FormatRecord */
    1458,  /* remote_EvaluateCondition */
    1502,  /* remote_GetFeatureCost */
    1564,  /* remote_EnumComponentCosts */
    1638,  /* remote_GetActionInfo */
    1706,  /* remote_CloseHandle */
};

static const MIDL_STUB_DESC IWineMsiRemote_StubDesc =
{
    (void *)& IWineMsiRemote___RpcServerInterface,
    MIDL_user_allocate,
    MIDL_user_free,
    {
        0,
    },
    0,
    0,
    0,
    0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};

static RPC_DISPATCH_FUNCTION IWineMsiRemote_table[] =
{
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    0
};
static RPC_DISPATCH_TABLE IWineMsiRemote_v0_0_DispatchTable =
{
    35,
    IWineMsiRemote_table
};

static const SERVER_ROUTINE IWineMsiRemote_ServerRoutineTable[] =
{
    (void *)s_remote_ViewClose,
    (void *)s_remote_ViewExecute,
    (void *)s_remote_ViewFetch,
    (void *)s_remote_ViewGetColumnInfo,
    (void *)s_remote_ViewGetError,
    (void *)s_remote_ViewModify,
    (void *)s_remote_DatabaseIsTablePersistent,
    (void *)s_remote_DatabaseGetPrimaryKeys,
    (void *)s_remote_DatabaseGetSummaryInformation,
    (void *)s_remote_DatabaseOpenView,
    (void *)s_remote_SummaryInfoGetPropertyCount,
    (void *)s_remote_SummaryInfoGetProperty,
    (void *)s_remote_GetActiveDatabase,
    (void *)s_remote_GetProperty,
    (void *)s_remote_SetProperty,
    (void *)s_remote_ProcessMessage,
    (void *)s_remote_DoAction,
    (void *)s_remote_Sequence,
    (void *)s_remote_GetTargetPath,
    (void *)s_remote_SetTargetPath,
    (void *)s_remote_GetSourcePath,
    (void *)s_remote_GetMode,
    (void *)s_remote_SetMode,
    (void *)s_remote_GetFeatureState,
    (void *)s_remote_SetFeatureState,
    (void *)s_remote_GetComponentState,
    (void *)s_remote_SetComponentState,
    (void *)s_remote_GetLanguage,
    (void *)s_remote_SetInstallLevel,
    (void *)s_remote_FormatRecord,
    (void *)s_remote_EvaluateCondition,
    (void *)s_remote_GetFeatureCost,
    (void *)s_remote_EnumComponentCosts,
    (void *)s_remote_GetActionInfo,
    (void *)s_remote_CloseHandle,
};

static const MIDL_SERVER_INFO IWineMsiRemote_ServerInfo =
{
    &IWineMsiRemote_StubDesc,
    IWineMsiRemote_ServerRoutineTable,
    __MIDL_ProcFormatString.Format,
    IWineMsiRemote_FormatStringOffsetTable,
    0,
    0,
    0,
    0
};

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure IWineMsiRemote::remote_ViewClose) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x0),	/* method 0 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 26 (parameter view) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 32 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 38 (procedure IWineMsiRemote::remote_ViewExecute) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x1),	/* method 1 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 64 (parameter view) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 70 (parameter record) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x74),	/* type offset = 116 */
/* 76 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 82 (procedure IWineMsiRemote::remote_ViewFetch) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x2),	/* method 2 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 108 (parameter view) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 114 (parameter record) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x7c),	/* type offset = 124 */
/* 120 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 126 (procedure IWineMsiRemote::remote_ViewGetColumnInfo) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 152 (parameter view) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 158 (parameter info) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 164 (parameter record) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x84),	/* type offset = 132 */
/* 170 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 176 (procedure IWineMsiRemote::remote_ViewGetError) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 202 (parameter view) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 208 (parameter column) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x8c),	/* type offset = 140 */
/* 214 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 220 (procedure IWineMsiRemote::remote_ViewModify) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x05,	/* 5 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 246 (parameter view) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 252 (parameter mode) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 258 (parameter record) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x68),	/* type offset = 104 */
/* 264 (parameter refreshed) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x98),	/* type offset = 152 */
/* 270 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 276 (procedure IWineMsiRemote::remote_DatabaseIsTablePersistent) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 302 (parameter db) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 308 (parameter table) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x9e),	/* type offset = 158 */
/* 314 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 320 (procedure IWineMsiRemote::remote_DatabaseGetPrimaryKeys) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x7),	/* method 7 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 346 (parameter db) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 352 (parameter table) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xa2),	/* type offset = 162 */
/* 358 (parameter keys) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0xa8),	/* type offset = 168 */
/* 364 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 370 (procedure IWineMsiRemote::remote_DatabaseGetSummaryInformation) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x8),	/* method 8 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x44,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 396 (parameter db) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 402 (parameter updatecount) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 408 (parameter suminfo) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x09,	/* FC_ULONG */
        0x0,
/* 414 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 420 (procedure IWineMsiRemote::remote_DatabaseOpenView) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x9),	/* method 9 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 446 (parameter db) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 452 (parameter query) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xb2),	/* type offset = 178 */
/* 458 (parameter view) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x09,	/* FC_ULONG */
        0x0,
/* 464 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 470 (procedure IWineMsiRemote::remote_SummaryInfoGetPropertyCount) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xa),	/* method 10 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x44,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 496 (parameter suminfo) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 502 (parameter count) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x09,	/* FC_ULONG */
        0x0,
/* 508 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 514 (procedure IWineMsiRemote::remote_SummaryInfoGetProperty) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xb),	/* method 11 */
        NdrFcShort(0x38),	/* stack size = 56 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x24),	/* server buffer = 36 */
        0x45,
        0x07,	/* 7 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 540 (parameter suminfo) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 546 (parameter property) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 552 (parameter type) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x09,	/* FC_ULONG */
        0x0,
/* 558 (parameter value) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 564 (parameter ft) */
        NdrFcShort(0x2112),	/* flags: must free, out, simple ref, srv size=8 */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0xc4),	/* type offset = 196 */
/* 570 (parameter buf) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0xd4),	/* type offset = 212 */
/* 576 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x30),	/* stack offset = 48 */
        0x08,	/* FC_LONG */
        0x0,
/* 582 (procedure IWineMsiRemote::remote_GetActiveDatabase) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xc),	/* method 12 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 608 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 614 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 620 (procedure IWineMsiRemote::remote_GetProperty) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xd),	/* method 13 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x47,
        0x05,	/* 5 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 646 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 652 (parameter property) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xda),	/* type offset = 218 */
/* 658 (parameter value) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0xe0),	/* type offset = 224 */
/* 664 (parameter size) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x09,	/* FC_ULONG */
        0x0,
/* 670 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 676 (procedure IWineMsiRemote::remote_SetProperty) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xe),	/* method 14 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 702 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 708 (parameter property) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xe8),	/* type offset = 232 */
/* 714 (parameter value) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0xec),	/* type offset = 236 */
/* 720 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 726 (procedure IWineMsiRemote::remote_ProcessMessage) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0xf),	/* method 15 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 752 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 758 (parameter message) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 764 (parameter record) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x68),	/* type offset = 104 */
/* 770 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 776 (procedure IWineMsiRemote::remote_DoAction) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x10),	/* method 16 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 802 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 808 (parameter action) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xf6),	/* type offset = 246 */
/* 814 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 820 (procedure IWineMsiRemote::remote_Sequence) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x11),	/* method 17 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 846 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 852 (parameter table) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xfa),	/* type offset = 250 */
/* 858 (parameter sequence) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 864 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 870 (procedure IWineMsiRemote::remote_GetTargetPath) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x12),	/* method 18 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 896 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 902 (parameter folder) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xfe),	/* type offset = 254 */
/* 908 (parameter value) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x104),	/* type offset = 260 */
/* 914 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 920 (procedure IWineMsiRemote::remote_SetTargetPath) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x13),	/* method 19 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 946 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 952 (parameter folder) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x10a),	/* type offset = 266 */
/* 958 (parameter value) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x10e),	/* type offset = 270 */
/* 964 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 970 (procedure IWineMsiRemote::remote_GetSourcePath) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x14),	/* method 20 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 996 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1002 (parameter folder) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x112),	/* type offset = 274 */
/* 1008 (parameter value) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x118),	/* type offset = 280 */
/* 1014 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 1020 (procedure IWineMsiRemote::remote_GetMode) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x15),	/* method 21 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1046 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1052 (parameter mode) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 1058 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1064 (procedure IWineMsiRemote::remote_SetMode) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x16),	/* method 22 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1090 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1096 (parameter mode) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 1102 (parameter state) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1108 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 1114 (procedure IWineMsiRemote::remote_GetFeatureState) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x17),	/* method 23 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x18),	/* server buffer = 24 */
        0x46,
        0x05,	/* 5 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1140 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1146 (parameter feature) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x11e),	/* type offset = 286 */
/* 1152 (parameter installed) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1158 (parameter action) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 1164 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 1170 (procedure IWineMsiRemote::remote_SetFeatureState) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x18),	/* method 24 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1196 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1202 (parameter feature) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x12a),	/* type offset = 298 */
/* 1208 (parameter state) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1214 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 1220 (procedure IWineMsiRemote::remote_GetComponentState) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x19),	/* method 25 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x18),	/* server buffer = 24 */
        0x46,
        0x05,	/* 5 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1246 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1252 (parameter component) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x12e),	/* type offset = 302 */
/* 1258 (parameter installed) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1264 (parameter action) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 1270 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 1276 (procedure IWineMsiRemote::remote_SetComponentState) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x1a),	/* method 26 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1302 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1308 (parameter component) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x13a),	/* type offset = 314 */
/* 1314 (parameter state) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1320 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 1326 (procedure IWineMsiRemote::remote_GetLanguage) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x1b),	/* method 27 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x6),	/* server buffer = 6 */
        0x44,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1352 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1358 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x06,	/* FC_SHORT */
        0x0,
/* 1364 (procedure IWineMsiRemote::remote_SetInstallLevel) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x1c),	/* method 28 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1390 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1396 (parameter level) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 1402 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1408 (procedure IWineMsiRemote::remote_FormatRecord) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x1d),	/* method 29 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1434 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1440 (parameter record) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x68),	/* type offset = 104 */
/* 1446 (parameter value) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x144),	/* type offset = 324 */
/* 1452 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 1458 (procedure IWineMsiRemote::remote_EvaluateCondition) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x1e),	/* method 30 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1484 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1490 (parameter condition) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x14a),	/* type offset = 330 */
/* 1496 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1502 (procedure IWineMsiRemote::remote_GetFeatureCost) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x1f),	/* method 31 */
        NdrFcShort(0x30),	/* stack size = 48 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x46,
        0x06,	/* 6 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1528 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1534 (parameter feature) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x14e),	/* type offset = 334 */
/* 1540 (parameter cost_tree) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1546 (parameter state) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 1552 (parameter cost) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 1558 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x28),	/* stack offset = 40 */
        0x08,	/* FC_LONG */
        0x0,
/* 1564 (procedure IWineMsiRemote::remote_EnumComponentCosts) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x20),	/* method 32 */
        NdrFcShort(0x40),	/* stack size = 64 */
        NdrFcShort(0x18),	/* client buffer = 24 */
        NdrFcShort(0x18),	/* server buffer = 24 */
        0x47,
        0x08,	/* 8 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1590 (parameter hinst) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1596 (parameter component) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x154),	/* type offset = 340 */
/* 1602 (parameter index) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1608 (parameter state) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 1614 (parameter drive) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x15c),	/* type offset = 348 */
/* 1620 (parameter cost) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x28),	/* stack offset = 40 */
        0x08,	/* FC_LONG */
        0x0,
/* 1626 (parameter temp) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x30),	/* stack offset = 48 */
        0x08,	/* FC_LONG */
        0x0,
/* 1632 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x38),	/* stack offset = 56 */
        0x08,	/* FC_LONG */
        0x0,
/* 1638 (procedure IWineMsiRemote::remote_GetActionInfo) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x21),	/* method 33 */
        NdrFcShort(0x38),	/* stack size = 56 */
        NdrFcShort(0x14),	/* client buffer = 20 */
        NdrFcShort(0x18),	/* server buffer = 24 */
        0x45,
        0x07,	/* 7 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1664 (parameter guid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x172),	/* type offset = 370 */
/* 1670 (parameter action) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x186),	/* type offset = 390 */
/* 1676 (parameter type) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 1682 (parameter dllname) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x192),	/* type offset = 402 */
/* 1688 (parameter function) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0x19a),	/* type offset = 410 */
/* 1694 (parameter hinst) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x28),	/* stack offset = 40 */
        0x09,	/* FC_ULONG */
        0x0,
/* 1700 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x30),	/* stack offset = 48 */
        0x08,	/* FC_LONG */
        0x0,
/* 1706 (procedure IWineMsiRemote::remote_CloseHandle) */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x22),	/* method 34 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1732 (parameter handle) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x08,	/* FC_LONG */
        0x0,
/* 1738 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (LPWSTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/*  4 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 6 (IStream *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x0000000c),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 24 (union ) */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x4),	/* 4 */
        NdrFcLong(0x0),	/* 0 */
        NdrFcShort(0x0),	/* No type */
        NdrFcLong(0x1),	/* 1 */
        NdrFcShort(0x8008),	/* Simple arm type: FC_LONG */
        NdrFcLong(0x3),	/* 3 */
        NdrFcShort(0xffd6),	/* Offset= -42 (2) */
        NdrFcLong(0x4),	/* 4 */
        NdrFcShort(0xffd4),	/* Offset= -44 (6) */
        NdrFcShort(0xffff),
/* 54 */
        0x2b,	/* FC_NON_ENCAPSULATED_UNION */
        0x9,	/* FC_ULONG */
        0x9,	/* Corr desc: field type, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0xfff8),	/* offset = -8 */
        NdrFcShort(0x1),
        NdrFcShort(0xffda),	/* Offset= -38 (24) */
/* 64 (struct wire_field) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x18),	/* 24 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (70) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffea),	/* Offset= -22 (54) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 82 (struct wire_field[]) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x9,	/* Corr desc: field count, FC_ULONG */
        0x57,	/* FC_ADD_1 */
        NdrFcShort(0xfff0),	/* offset = -16 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffdc),	/* Offset= -36 (64) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 104 (struct wire_record) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0xffe6),	/* Offset= -26 (82) */
        NdrFcShort(0x0),	/* Offset= 0 (110) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x0b,	/* FC_HYPER */
        0x5b,	/* FC_END */
/* 116 (struct wire_record *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfff2),	/* Offset= -14 (104) */
/* 120 (struct wire_record *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffee),	/* Offset= -18 (104) */
/* 124 (struct wire_record **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (120) */
/* 128 (struct wire_record *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe6),	/* Offset= -26 (104) */
/* 132 (struct wire_record **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (128) */
/* 136 (LPWSTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 138 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 140 (LPWSTR *) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (136) */
/* 144 (struct wire_record *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffd6),	/* Offset= -42 (104) */
/* 148 (struct wire_record *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffd2),	/* Offset= -46 (104) */
/* 152 (struct wire_record **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (148) */
/* 156 (LPCWSTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 158 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 160 (LPCWSTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 162 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 164 (struct wire_record *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffc2),	/* Offset= -62 (104) */
/* 168 (struct wire_record **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (164) */
/* 172 (MSIHANDLE *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 176 (LPCWSTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 178 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 180 (MSIHANDLE *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 184 (UINT *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 188 (UINT *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 192 (INT *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 196 (FILETIME) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 204 (FILETIME *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfff6),	/* Offset= -10 (196) */
/* 208 (LPWSTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 210 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 212 (LPWSTR *) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (208) */
/* 216 (LPCWSTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 218 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 220 (LPWSTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 222 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 224 (LPWSTR *) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (220) */
/* 228 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 232 (LPCWSTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 234 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 236 (LPCWSTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 238 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 240 (struct wire_record *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff76),	/* Offset= -138 (104) */
/* 244 (LPCWSTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 246 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 248 (LPCWSTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 250 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 252 (LPCWSTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 254 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 256 (LPWSTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 258 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 260 (LPWSTR *) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (256) */
/* 264 (LPCWSTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 266 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 268 (LPCWSTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 270 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 272 (LPCWSTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 274 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 276 (LPWSTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 278 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 280 (LPWSTR *) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (276) */
/* 284 (LPCWSTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 286 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 288 (INSTALLSTATE *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 292 (INSTALLSTATE *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 296 (LPCWSTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 298 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 300 (LPCWSTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 302 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 304 (INSTALLSTATE *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 308 (INSTALLSTATE *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 312 (LPCWSTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 314 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 316 (struct wire_record *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff2a),	/* Offset= -214 (104) */
/* 320 (LPWSTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 322 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 324 (LPWSTR *) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (320) */
/* 328 (LPCWSTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 330 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 332 (LPCWSTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 334 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 336 (INT *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 340 (LPCWSTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 342 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 344 (LPWSTR) */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0x2),
/* 348 */
        0x25,	/* FC_C_WSTRING */
        0x44,	/* FC_STRING_SIZED */
        0x40, /* Corr desc: constant, val = 3 */
        0x0,
        NdrFcShort(0x3),
        NdrFcShort(0x1),
/* 356 (INT *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 360 (INT *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 364 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 370 (GUID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (364) */
        0x5b,	/* FC_END */
/* 382 (const GUID *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfff2),	/* Offset= -14 (370) */
/* 386 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 388 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 390 (WCHAR **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (386) */
/* 394 (int *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 398 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 400 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 402 (WCHAR **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (398) */
/* 406 (char *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 408 */
        0x22,	/* FC_C_CSTRING */
        0x5c,	/* FC_PAD */
/* 410 (char **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (406) */
/* 414 (MSIHANDLE *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
        0x0
    }
};

